{
  "hash": "e14d0e5d7eae796c33c117535f8d8607",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Bikeshare Space-Time Prediction\"\nsubtitle: \"CPLN 5080 - Spring 2026\"\nauthor: \"Coco Zhou\"\ndate: April 14, 2016\nformat:\n  html:\n    code-fold: show\n    code-tools: true\n    toc: true\n    toc-depth: 3\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\neditor: visual\nexecute:\n  warning: false\n  message: false\n---\n# Introduction\nThis report focuses on comparing Q1 and Q3 ridership patterns, with particular attention to Q3 as the higher-demand season. I chose these quarters to examine how model performance changes across different seasonal conditions, especially between a lower-demand winter period and a busier summer period. This comparison is useful because bike-share demand is not constant throughout the year as summer ridership tends to be higher and more variable, while winter demand is generally lower and more stable. By analyzing both quarters, the report can better assess whether the models perform consistently across seasons and whether some periods are more difficult to predict than others.\n\n# SET UP\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(lubridate)\nlibrary(sf)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(riem)  # For Philadelphia weather from ASOS stations\n\nlibrary(viridis) # color scales for visualization\nlibrary(knitr)\nlibrary(kableExtra)\nlibrary(patchwork)\n\n\nlibrary(here)\noptions(scipen = 999) # Get rid of scientific notation to make it look tidier\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplotTheme <- theme_minimal() +\n  theme(\n    plot.title    = element_text(size = 14, face = \"bold\"),\n    plot.subtitle = element_text(size = 10),\n    plot.caption  = element_text(size = 8),\n    axis.text.x   = element_text(size = 10, angle = 45, hjust = 1),\n    axis.text.y   = element_text(size = 10),\n    axis.title    = element_text(size = 11, face = \"bold\"),\n    panel.grid.major = element_line(colour = \"#D0D0D0\", linewidth = 0.2),\n    panel.grid.minor = element_blank(),\n    axis.ticks    = element_blank(),\n    legend.position = \"right\"\n  )\n\nmapTheme <- theme_void() +\n  theme(\n    plot.title    = element_text(size = 14, face = \"bold\"),\n    plot.subtitle = element_text(size = 10),\n    plot.caption  = element_text(size = 8),\n    legend.position  = \"right\",\n    plot.margin      = margin(1, 1, 1, 1, \"cm\"),\n    legend.key.height = unit(1, \"cm\"),\n    legend.key.width  = unit(0.2, \"cm\")\n  )\n\npalette5 <- c(\"#eff3ff\", \"#bdd7e7\", \"#6baed6\", \"#3182bd\", \"#08519c\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncensus_api_key(Sys.getenv(\"CENSUS_API_KEY\"))\n\n#Use the following code if you're not able to access the key in your environment\n#census_api_key(\"yourkeyhere\", install=TRUE, overwrite=TRUE)\n```\n:::\n\n\n# IMPORT AND PREP DATA Q3\n\n## Load Indego Trip Data (Q2 2025)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Read Q3 2025 data\nindego <- read_csv(\"data/indego-trips-2025-q3.csv\")\n\n# Quick look at the data\nglimpse(indego)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 465,464\nColumns: 15\n$ trip_id             <dbl> 1203073573, 1203073759, 1203073753, 1203073877, 12…\n$ duration            <dbl> 10, 19, 16, 19, 2, 6, 20, 4, 52, 3, 31, 9, 10, 9, …\n$ start_time          <chr> \"7/1/2025 0:06\", \"7/1/2025 0:11\", \"7/1/2025 0:13\",…\n$ end_time            <chr> \"7/1/2025 0:16\", \"7/1/2025 0:30\", \"7/1/2025 0:29\",…\n$ start_station       <dbl> 3163, 3304, 3394, 3207, 3061, 3320, 3201, 3078, 32…\n$ start_lat           <dbl> 39.94974, 39.94234, 39.92400, 39.95441, 39.95425, …\n$ start_lon           <dbl> -75.18097, -75.15399, -75.16959, -75.19200, -75.17…\n$ end_station         <dbl> 3374, 3315, 3394, 3368, 3156, 3320, 3196, 3235, 32…\n$ end_lat             <dbl> 39.97280, 39.94235, 39.92400, 39.97647, 39.95381, …\n$ end_lon             <dbl> -75.17971, -75.21138, -75.16959, -75.17362, -75.17…\n$ bike_id             <chr> \"31674\", \"29473\", \"27889\", \"31825\", \"25400\", \"3172…\n$ plan_duration       <dbl> 30, 1, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,…\n$ trip_route_category <chr> \"One Way\", \"One Way\", \"Round Trip\", \"One Way\", \"On…\n$ passholder_type     <chr> \"Indego30\", \"Walk-up\", \"Indego30\", \"Indego30\", \"In…\n$ bike_type           <chr> \"electric\", \"electric\", \"electric\", \"electric\", \"e…\n```\n\n\n:::\n:::\n\n\n## Examine the Data Structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# How many trips?\ncat(\"Total trips in Q3 2025:\", nrow(indego), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTotal trips in Q3 2025: 465464 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Date range\ncat(\"Date range:\", \n    min(mdy_hm(indego$start_time)), \"to\", \n    max(mdy_hm(indego$start_time)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDate range: 1751328360 to 1759276680 \n```\n\n\n:::\n\n```{.r .cell-code}\n# How many unique stations?\ncat(\"Unique start stations:\", length(unique(indego$start_station)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nUnique start stations: 284 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Trip types\ntable(indego$trip_route_category)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   One Way Round Trip \n    434518      30946 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Passholder types\ntable(indego$passholder_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n Day Pass  Indego30 Indego365      NULL   Walk-up \n    18418    252897    157695         5     36449 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Bike types\ntable(indego$bike_type)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nelectric standard \n  299515   165949 \n```\n\n\n:::\n:::\n\n\n## Create Time Bins\n\n\n::: {.cell}\n\n```{.r .cell-code}\nindego <- indego %>%\n  mutate(\n    # Parse datetime\n    start_datetime = mdy_hm(start_time),\n    end_datetime = mdy_hm(end_time),\n    \n    # Create hourly bins\n    interval60 = floor_date(start_datetime, unit = \"hour\"),\n    \n    # Extract time features\n    week = week(interval60),\n    month = month(interval60, label = TRUE),\n    dotw = wday(interval60, label = TRUE),\n    hour = hour(interval60),\n    date = as.Date(interval60),\n    \n    # Create useful indicators\n    weekend = ifelse(dotw %in% c(\"Sat\", \"Sun\"), 1, 0),\n    rush_hour = ifelse(hour %in% c(7, 8, 9, 16, 17, 18), 1, 0)\n  )\n\n# Look at temporal features\nhead(indego %>% select(start_datetime, interval60, week, dotw, hour, weekend))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 6\n  start_datetime      interval60           week dotw   hour weekend\n  <dttm>              <dttm>              <dbl> <ord> <int>   <dbl>\n1 2025-07-01 00:06:00 2025-07-01 00:00:00    26 Tue       0       0\n2 2025-07-01 00:11:00 2025-07-01 00:00:00    26 Tue       0       0\n3 2025-07-01 00:13:00 2025-07-01 00:00:00    26 Tue       0       0\n4 2025-07-01 00:16:00 2025-07-01 00:00:00    26 Tue       0       0\n5 2025-07-01 00:16:00 2025-07-01 00:00:00    26 Tue       0       0\n6 2025-07-01 00:18:00 2025-07-01 00:00:00    26 Tue       0       0\n```\n\n\n:::\n:::\n\n\n#EDA OF INDEGO DATA\n\n## Trips Over Time\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Daily trip counts\ndaily_trips <- indego %>%\n  group_by(date) %>%\n  summarize(trips = n())\n\nggplot(daily_trips, aes(x = date, y = trips)) +\n  geom_line(color = \"#3182bd\", linewidth = 1) +\n  geom_smooth(se = FALSE, color = \"red\", linetype = \"dashed\") +\n  labs(\n    title = \"Indego Daily Ridership - Q3 2025\",\n    subtitle = \"Spring demand patterns in Philadelphia\",\n    x = \"Date\",\n    y = \"Daily Trips\",\n    caption = \"Source: Indego bike share\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](lab5_files/figure-html/trips_over_time-1.png){width=672}\n:::\n:::\n\n\nDuring Summer 2025, Indego bike-share ridership in Philadelphia stayed relatively high and showed an overall upward trend. Although daily trips fluctuated a lot, with regular peaks and drops that suggest a weekly pattern, the red dashed trend line indicates that ridership generally increased from just above 4,000 trips in early July to around 5,600 by late September. Overall, the graph suggests growing demand for bike-share over the summer despite short-term variation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfly_eagles_fly <- daily_trips %>% filter(date == \"2025-09-01\")\n\ntypical_boring_monday <- indego %>%\n  filter(dotw == \"Mon\", date != \"2025-09-01\") %>%\n  group_by(date) %>%\n  summarize(trips = n()) %>%\n  summarize(avg_monday_trips = mean(trips))\n\nprint(fly_eagles_fly)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 2\n  date       trips\n  <date>     <int>\n1 2025-09-01  4664\n```\n\n\n:::\n\n```{.r .cell-code}\nprint(typical_boring_monday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 1\n  avg_monday_trips\n             <dbl>\n1            4962.\n```\n\n\n:::\n:::\n\n\nOn September 1, 2025, Indego recorded 4,664 trips, compared with an average of 4,962 trips for other Mondays, so ridership was about 298 trips lower than usual, or roughly 6% below the typical Monday level. This suggests that bike-share use was slightly reduced on that day, which makes sense because September 1, 2025 was Labor Day, a national holiday. Even though holidays can increase recreational riding for some people, they often reduce regular commuting trips, which likely pulled total ridership below the usual Monday average.\n\n## Hourly Patterns\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Average trips by hour and day type\nhourly_patterns <- indego %>%\n  group_by(hour, weekend) %>%\n  summarize(avg_trips = n() / n_distinct(date)) %>%\n  mutate(day_type = ifelse(weekend == 1, \"Weekend\", \"Weekday\"))\n\nggplot(hourly_patterns, aes(x = hour, y = avg_trips, color = day_type)) +\n  geom_line(linewidth = 1.2) +\n  scale_color_manual(values = c(\"Weekday\" = \"#08519c\", \"Weekend\" = \"#6baed6\")) +\n  labs(\n    title = \"Average Hourly Ridership Patterns\",\n    subtitle = \"Clear commute patterns on weekdays\",\n    x = \"Hour of Day\",\n    y = \"Average Trips per Hour\",\n    color = \"Day Type\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](lab5_files/figure-html/hourly_patterns-1.png){width=672}\n:::\n:::\n\n\n## Top Stations\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Most popular origin stations\ntop_stations <- indego %>%\n  count(start_station, start_lat, start_lon, name = \"trips\") %>%\n  arrange(desc(trips)) %>%\n  head(20)\n\nkable(top_stations, \n      caption = \"Top 20 Indego Stations by Trip Origins\",\n      format.args = list(big.mark = \",\")) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Top 20 Indego Stations by Trip Origins</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:right;\"> start_station </th>\n   <th style=\"text-align:right;\"> start_lat </th>\n   <th style=\"text-align:right;\"> start_lon </th>\n   <th style=\"text-align:right;\"> trips </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:right;\"> 3,010 </td>\n   <td style=\"text-align:right;\"> 39.94711 </td>\n   <td style=\"text-align:right;\"> -75.16618 </td>\n   <td style=\"text-align:right;\"> 7,716 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,032 </td>\n   <td style=\"text-align:right;\"> 39.94527 </td>\n   <td style=\"text-align:right;\"> -75.17971 </td>\n   <td style=\"text-align:right;\"> 5,884 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,213 </td>\n   <td style=\"text-align:right;\"> 39.93887 </td>\n   <td style=\"text-align:right;\"> -75.16663 </td>\n   <td style=\"text-align:right;\"> 5,660 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,163 </td>\n   <td style=\"text-align:right;\"> 39.94974 </td>\n   <td style=\"text-align:right;\"> -75.18097 </td>\n   <td style=\"text-align:right;\"> 5,174 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,359 </td>\n   <td style=\"text-align:right;\"> 39.94888 </td>\n   <td style=\"text-align:right;\"> -75.16978 </td>\n   <td style=\"text-align:right;\"> 4,681 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,185 </td>\n   <td style=\"text-align:right;\"> 39.95169 </td>\n   <td style=\"text-align:right;\"> -75.15888 </td>\n   <td style=\"text-align:right;\"> 4,670 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,028 </td>\n   <td style=\"text-align:right;\"> 39.94061 </td>\n   <td style=\"text-align:right;\"> -75.14958 </td>\n   <td style=\"text-align:right;\"> 4,607 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,020 </td>\n   <td style=\"text-align:right;\"> 39.94855 </td>\n   <td style=\"text-align:right;\"> -75.19007 </td>\n   <td style=\"text-align:right;\"> 4,556 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,022 </td>\n   <td style=\"text-align:right;\"> 39.95472 </td>\n   <td style=\"text-align:right;\"> -75.18323 </td>\n   <td style=\"text-align:right;\"> 4,475 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,066 </td>\n   <td style=\"text-align:right;\"> 39.94561 </td>\n   <td style=\"text-align:right;\"> -75.17348 </td>\n   <td style=\"text-align:right;\"> 4,353 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,059 </td>\n   <td style=\"text-align:right;\"> 39.96244 </td>\n   <td style=\"text-align:right;\"> -75.16121 </td>\n   <td style=\"text-align:right;\"> 4,265 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,063 </td>\n   <td style=\"text-align:right;\"> 39.94633 </td>\n   <td style=\"text-align:right;\"> -75.16980 </td>\n   <td style=\"text-align:right;\"> 4,230 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,161 </td>\n   <td style=\"text-align:right;\"> 39.95486 </td>\n   <td style=\"text-align:right;\"> -75.18091 </td>\n   <td style=\"text-align:right;\"> 4,223 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,101 </td>\n   <td style=\"text-align:right;\"> 39.94295 </td>\n   <td style=\"text-align:right;\"> -75.15955 </td>\n   <td style=\"text-align:right;\"> 4,183 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,054 </td>\n   <td style=\"text-align:right;\"> 39.96250 </td>\n   <td style=\"text-align:right;\"> -75.17420 </td>\n   <td style=\"text-align:right;\"> 4,117 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,030 </td>\n   <td style=\"text-align:right;\"> 39.93935 </td>\n   <td style=\"text-align:right;\"> -75.15716 </td>\n   <td style=\"text-align:right;\"> 3,986 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,362 </td>\n   <td style=\"text-align:right;\"> 39.94816 </td>\n   <td style=\"text-align:right;\"> -75.16226 </td>\n   <td style=\"text-align:right;\"> 3,965 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,061 </td>\n   <td style=\"text-align:right;\"> 39.95425 </td>\n   <td style=\"text-align:right;\"> -75.17761 </td>\n   <td style=\"text-align:right;\"> 3,716 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,057 </td>\n   <td style=\"text-align:right;\"> 39.96439 </td>\n   <td style=\"text-align:right;\"> -75.17987 </td>\n   <td style=\"text-align:right;\"> 3,668 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:right;\"> 3,296 </td>\n   <td style=\"text-align:right;\"> 39.95134 </td>\n   <td style=\"text-align:right;\"> -75.16758 </td>\n   <td style=\"text-align:right;\"> 3,665 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n# PUT DATA IN CONTEXT\n\n## Load Philadelphia Census Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get Philadelphia census tracts\nphilly_census <- get_acs(\n  geography = \"tract\",\n  variables = c(\n    \"B01003_001\",  # Total population\n    \"B19013_001\",  # Median household income\n    \"B08301_001\",  # Total commuters\n    \"B08301_010\",  # Commute by transit\n    \"B02001_002\",  # White alone\n    \"B25077_001\"   # Median home value\n  ),\n  state = \"PA\",\n  county = \"Philadelphia\",\n  year = 2022,\n  geometry = TRUE,\n  output = \"wide\"\n) %>%\n  rename(\n    Total_Pop = B01003_001E,\n    Med_Inc = B19013_001E,\n    Total_Commuters = B08301_001E,\n    Transit_Commuters = B08301_010E,\n    White_Pop = B02001_002E,\n    Med_Home_Value = B25077_001E\n  ) %>%\n  mutate(\n    Percent_Taking_Transit = (Transit_Commuters / Total_Commuters) * 100,\n    Percent_White = (White_Pop / Total_Pop) * 100\n  ) %>%\n  st_transform(crs = 4326)  #transforming to WGS84 for lat/lon matching, currently in NAD83\n\n# Check the data\nglimpse(philly_census)\n```\n:::\n\n\n## Map Philadelphia Context\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Map median income\nggplot() +\n  geom_sf(data = philly_census, aes(fill = Med_Inc), color = NA) +\n  scale_fill_viridis(\n    option = \"viridis\",\n    name = \"Median\\nIncome\",\n    labels = scales::dollar\n  ) +\n  labs(\n    title = \"Philadelphia Median Household Income by Census Tract\",\n    subtitle = \"Context for understanding bike share demand patterns\"\n  ) +\n  # Stations \n  geom_point(\n    data = indego,\n    aes(x = start_lon, y = start_lat),\n    color = \"red\", size = 0.25, alpha = 0.6\n  ) +\n  mapTheme\n```\n\n::: {.cell-output-display}\n![](lab5_files/figure-html/map_philly-1.png){width=672}\n:::\n:::\n\n\n## Join Census Data to Stations\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create sf object for stations\nstations_sf <- indego %>%\n  distinct(start_station, start_lat, start_lon) %>%\n  filter(!is.na(start_lat), !is.na(start_lon)) %>%\n  st_as_sf(coords = c(\"start_lon\", \"start_lat\"), crs = 4326)\n\n# Spatial join to get census tract for each station\nstations_census <- st_join(stations_sf, philly_census, left = TRUE) %>%\n  st_drop_geometry()\n\n# Look at the result - investigate whether all of the stations joined to census data -- according to the map above there are stations in non-residential tracts.\n\nstations_for_map <- indego %>%\n  distinct(start_station, start_lat, start_lon) %>%\n  filter(!is.na(start_lat), !is.na(start_lon)) %>%\n  left_join(\n    stations_census %>% select(start_station, Med_Inc),\n    by = \"start_station\"\n  ) %>%\n  mutate(has_census = !is.na(Med_Inc))\n\n# Add back to trip data\nindego_census <- indego %>%\n  left_join(\n    stations_census %>% \n      select(start_station, Med_Inc, Percent_Taking_Transit, \n             Percent_White, Total_Pop),\n    by = \"start_station\"\n  )\n\n\n# Prepare data for visualization\nstations_for_map <- indego %>%\n  distinct(start_station, start_lat, start_lon) %>%\n  filter(!is.na(start_lat), !is.na(start_lon)) %>%\n  left_join(\n    stations_census %>% select(start_station, Med_Inc),\n    by = \"start_station\"\n  ) %>%\n  mutate(has_census = !is.na(Med_Inc))\n\n# Create the map showing problem stations\nggplot() +\n  geom_sf(data = philly_census, aes(fill = Med_Inc), color = \"white\", size = 0.1) +\n  scale_fill_viridis(\n    option = \"viridis\",\n    name = \"Median\\nIncome\",\n    labels = scales::dollar,\n    na.value = \"grey90\"\n  ) +\n  # Stations with census data (small grey dots)\n  geom_point(\n    data = stations_for_map %>% filter(has_census),\n    aes(x = start_lon, y = start_lat),\n    color = \"grey30\", size = 1, alpha = 0.6\n  ) +\n  # Stations WITHOUT census data (red X marks the spot)\n  geom_point(\n    data = stations_for_map %>% filter(!has_census),\n    aes(x = start_lon, y = start_lat),\n    color = \"red\", size = 1, shape = 4, stroke = 1.5\n  ) +\n  labs(\n    title = \"Philadelphia Median Household Income by Census Tract\",\n    subtitle = \"Indego stations shown (RED = no census data match)\",\n    caption = \"Red X marks indicate stations that didn't join to census tracts\"\n  ) +\n  mapTheme\n```\n\n::: {.cell-output-display}\n![](lab5_files/figure-html/join_census_to_stations-1.png){width=672}\n:::\n:::\n\n\n## Dealing with missing data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Identify which stations to keep\nvalid_stations <- stations_census %>%\n  filter(!is.na(Med_Inc)) %>%\n  pull(start_station)\n\n# Filter trip data to valid stations only\nindego_census <- indego %>%\n  filter(start_station %in% valid_stations) %>%\n  left_join(\n    stations_census %>% \n      select(start_station, Med_Inc, Percent_Taking_Transit, \n             Percent_White, Total_Pop),\n    by = \"start_station\"\n  )\n```\n:::\n\n\n## Get Weather Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get weather from Philadelphia International Airport (KPHL)\n# This covers Q3 2024: July 1 - September 30\nweather_data <- riem_measures(\n  station = \"PHL\",  # Philadelphia International Airport\n  date_start = \"2025-07-01\",\n  date_end = \"2025-09-30\"\n)\n\n# Process weather data\nweather_processed <- weather_data %>%\n  mutate(\n    interval60 = floor_date(valid, unit = \"hour\"),\n    Temperature = tmpf,  # Temperature in Fahrenheit\n    Precipitation = ifelse(is.na(p01i), 0, p01i),  # Hourly precip in inches\n    Wind_Speed = sknt  # Wind speed in knots\n  ) %>%\n  select(interval60, Temperature, Precipitation, Wind_Speed) %>%\n  distinct()\n\n# Check for missing hours and interpolate if needed\nweather_complete <- weather_processed %>%\n  complete(interval60 = seq(min(interval60), max(interval60), by = \"hour\")) %>%\n  fill(Temperature, Precipitation, Wind_Speed, .direction = \"down\")\n\n# Look at the weather\nsummary(weather_complete %>% select(Temperature, Precipitation, Wind_Speed))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Temperature    Precipitation        Wind_Speed   \n Min.   :57.00   Min.   :0.000000   Min.   : 0.00  \n 1st Qu.:70.00   1st Qu.:0.000000   1st Qu.: 4.00  \n Median :76.00   Median :0.000000   Median : 6.00  \n Mean   :75.72   Mean   :0.008019   Mean   : 6.42  \n 3rd Qu.:81.00   3rd Qu.:0.000000   3rd Qu.: 9.00  \n Max.   :98.00   Max.   :1.390000   Max.   :29.00  \n```\n\n\n:::\n:::\n\n\n## Visualize Weather Patterns\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(weather_complete, aes(x = interval60, y = Temperature)) +\n  geom_line(color = \"#3182bd\", alpha = 0.7) +\n  geom_smooth(se = FALSE, color = \"red\") +\n  labs(\n    title = \"Philadelphia Temperature - Q3 2025\",\n    subtitle = \"Winter to early spring transition\",\n    x = \"Date\",\n    y = \"Temperature (°F)\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](lab5_files/figure-html/visualize-weather-1.png){width=672}\n:::\n:::\n\n\n# CREATE SPACE-TIME PANEL\n\n## Aggregate Trips to Station-Hour Level\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Count trips by station-hour\ntrips_panel <- indego_census %>%\n  group_by(interval60, start_station, start_lat, start_lon,\n           Med_Inc, Percent_Taking_Transit, Percent_White, Total_Pop) %>%\n  summarize(Trip_Count = n()) %>%\n  ungroup()\n\n# How many station-hour observations?\nnrow(trips_panel)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 214178\n```\n\n\n:::\n\n```{.r .cell-code}\n# How many unique stations?\nlength(unique(trips_panel$start_station))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 263\n```\n\n\n:::\n\n```{.r .cell-code}\n# How many unique hours?\nlength(unique(trips_panel$interval60))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2208\n```\n\n\n:::\n:::\n\n\n## Create Complete Panel Structure\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate expected panel size\nn_stations <- length(unique(trips_panel$start_station))\nn_hours <- length(unique(trips_panel$interval60))\nexpected_rows <- n_stations * n_hours\n\ncat(\"Expected panel rows:\", format(expected_rows, big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nExpected panel rows: 580,704 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Current rows:\", format(nrow(trips_panel), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCurrent rows: 214,178 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Missing rows:\", format(expected_rows - nrow(trips_panel), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nMissing rows: 366,526 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create complete panel\nstudy_panel <- expand.grid(\n  interval60 = unique(trips_panel$interval60),\n  start_station = unique(trips_panel$start_station)\n) %>%\n  # Join trip counts\n  left_join(trips_panel, by = c(\"interval60\", \"start_station\")) %>%\n  # Replace NA trip counts with 0\n  mutate(Trip_Count = replace_na(Trip_Count, 0))\n\n# Fill in station attributes (they're the same for all hours)\nstation_attributes <- trips_panel %>%\n  group_by(start_station) %>%\n  summarize(\n    start_lat = first(start_lat),\n    start_lon = first(start_lon),\n    Med_Inc = first(Med_Inc),\n    Percent_Taking_Transit = first(Percent_Taking_Transit),\n    Percent_White = first(Percent_White),\n    Total_Pop = first(Total_Pop)\n  )\n\nstudy_panel <- study_panel %>%\n  left_join(station_attributes, by = \"start_station\")\n\n# Verify we have complete panel\ncat(\"Complete panel rows:\", format(nrow(study_panel), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nComplete panel rows: 580,704 \n```\n\n\n:::\n:::\n\n\n\n## Add Time Features\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy_panel <- study_panel %>%\n  mutate(\n    week = week(interval60),\n    month = month(interval60, label = TRUE),\n    dotw = wday(interval60, label = TRUE),\n    hour = hour(interval60),\n    date = as.Date(interval60),\n    weekend = ifelse(dotw %in% c(\"Sat\", \"Sun\"), 1, 0),\n    rush_hour = ifelse(hour %in% c(7, 8, 9, 16, 17, 18), 1, 0)\n  )\n```\n:::\n\n\n## Join Weather Data\n\n::: {.cell}\n\n```{.r .cell-code}\nstudy_panel <- study_panel %>%\n  left_join(weather_complete, by = \"interval60\")\n\n# Check for missing values\nsummary(study_panel %>% select(Trip_Count, Temperature, Precipitation))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Trip_Count       Temperature    Precipitation  \n Min.   : 0.0000   Min.   :57.00   Min.   :0.000  \n 1st Qu.: 0.0000   1st Qu.:70.00   1st Qu.:0.000  \n Median : 0.0000   Median :76.00   Median :0.000  \n Mean   : 0.7236   Mean   :75.72   Mean   :0.008  \n 3rd Qu.: 1.0000   3rd Qu.:81.00   3rd Qu.:0.000  \n Max.   :22.0000   Max.   :98.00   Max.   :1.390  \n                   NA's   :6312    NA's   :6312   \n```\n\n\n:::\n:::\n\n\n# CREATE TEMPORAL LAG VARIABLES\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sort by station and time\nstudy_panel <- study_panel %>%\n  arrange(start_station, interval60)\n\n# Create lag variables WITHIN each station\nstudy_panel <- study_panel %>%\n  group_by(start_station) %>%\n  mutate(\n    lag1Hour = lag(Trip_Count, 1),\n    lag2Hours = lag(Trip_Count, 2),\n    lag3Hours = lag(Trip_Count, 3),\n    lag12Hours = lag(Trip_Count, 12),\n    lag1day = lag(Trip_Count, 24)\n  ) %>%\n  ungroup()\n\n# Remove rows with NA lags (first 24 hours for each station)\nstudy_panel_complete <- study_panel %>%\n  filter(!is.na(lag1day))\n\ncat(\"Rows after removing NA lags:\", format(nrow(study_panel_complete), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows after removing NA lags: 708,785 \n```\n\n\n:::\n:::\n\n\n## Visualize Lag Correlations\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sample one station to visualize\nexample_station <- study_panel_complete %>%\n  filter(start_station == first(start_station)) %>%\n  head(168)  # One week\n\n# Plot actual vs lagged demand\nggplot(example_station, aes(x = interval60)) +\n  geom_line(aes(y = Trip_Count, color = \"Current\"), linewidth = 1) +\n  geom_line(aes(y = lag1Hour, color = \"1 Hour Ago\"), linewidth = 1, alpha = 0.7) +\n  geom_line(aes(y = lag1day, color = \"24 Hours Ago\"), linewidth = 1, alpha = 0.7) +\n  scale_color_manual(values = c(\n    \"Current\" = \"#08519c\",\n    \"1 Hour Ago\" = \"#3182bd\",\n    \"24 Hours Ago\" = \"#6baed6\"\n  )) +\n  labs(\n    title = \"Temporal Lag Patterns at One Station\",\n    subtitle = \"Past demand predicts future demand\",\n    x = \"Date-Time\",\n    y = \"Trip Count\",\n    color = \"Time Period\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](lab5_files/figure-html/lag_correlations-1.png){width=672}\n:::\n:::\n\n\n# TEMPORAL TRAIN/TEST SPLIT\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Split by week\n# Q3 has weeks 27-40 (July-Spet)\n# Train on weeks 27-35 \n# Test on weeks 36-40 \n\n# Which stations have trips in BOTH early and late periods?\nearly_stations <- study_panel_complete %>%\n  filter(week < 36) %>%\n  filter(Trip_Count > 0) %>%\n  distinct(start_station) %>%\n  pull(start_station)\n\nlate_stations <- study_panel_complete %>%\n  filter(week >= 36) %>%\n  filter(Trip_Count > 0) %>%\n  distinct(start_station) %>%\n  pull(start_station)\n\n# Keep only stations that appear in BOTH periods\ncommon_stations <- intersect(early_stations, late_stations)\n\n\n# Filter panel to only common stations\nstudy_panel_complete <- study_panel_complete %>%\n  filter(start_station %in% common_stations)\n\n# NOW create train/test split\ntrain <- study_panel_complete %>%\n  filter(week < 36)\n\ntest <- study_panel_complete %>%\n  filter(week >= 36)\n\ncat(\"Training observations:\", format(nrow(train), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining observations: 501,541 \n```\n\n\n:::\n:::\n\n\n#BUILD PREDICTIVE MODELS\n\n## Model 1: Baseline (Time + Weather)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create day of week factor with treatment (dummy) coding\ntrain <- train %>%\n  mutate(dotw_simple = factor(dotw, levels = c(\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\")))\n\n# Set contrasts to treatment coding (dummy variables)\ncontrasts(train$dotw_simple) <- contr.treatment(7)\n\n# Now run the model\nmodel1 <- lm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation,\n  data = train\n)\n\nsummary(model1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + \n    Precipitation, data = train)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.7125 -0.7561 -0.2121  0.2110 21.1067 \n\nCoefficients:\n                    Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)        0.4115692  0.0261453  15.742 < 0.0000000000000002 ***\nas.factor(hour)1  -0.0540262  0.0117895  -4.583    0.000004593990039 ***\nas.factor(hour)2  -0.1261545  0.0119723 -10.537 < 0.0000000000000002 ***\nas.factor(hour)3  -0.1774976  0.0119619 -14.839 < 0.0000000000000002 ***\nas.factor(hour)4  -0.1673862  0.0118130 -14.170 < 0.0000000000000002 ***\nas.factor(hour)5  -0.0559641  0.0121381  -4.611    0.000004015439965 ***\nas.factor(hour)6   0.1840261  0.0118983  15.467 < 0.0000000000000002 ***\nas.factor(hour)7   0.4500867  0.0118841  37.873 < 0.0000000000000002 ***\nas.factor(hour)8   0.9366676  0.0118247  79.213 < 0.0000000000000002 ***\nas.factor(hour)9   0.6136735  0.0119565  51.326 < 0.0000000000000002 ***\nas.factor(hour)10  0.4823405  0.0118642  40.655 < 0.0000000000000002 ***\nas.factor(hour)11  0.5258989  0.0114750  45.830 < 0.0000000000000002 ***\nas.factor(hour)12  0.6141261  0.0116979  52.499 < 0.0000000000000002 ***\nas.factor(hour)13  0.6775067  0.0118321  57.260 < 0.0000000000000002 ***\nas.factor(hour)14  0.7451786  0.0116539  63.942 < 0.0000000000000002 ***\nas.factor(hour)15  0.8546126  0.0116993  73.048 < 0.0000000000000002 ***\nas.factor(hour)16  1.0712931  0.0119723  89.481 < 0.0000000000000002 ***\nas.factor(hour)17  1.4012597  0.0120098 116.676 < 0.0000000000000002 ***\nas.factor(hour)18  1.0581635  0.0120162  88.061 < 0.0000000000000002 ***\nas.factor(hour)19  0.8235956  0.0120580  68.303 < 0.0000000000000002 ***\nas.factor(hour)20  0.5860658  0.0119470  49.055 < 0.0000000000000002 ***\nas.factor(hour)21  0.4237912  0.0117910  35.942 < 0.0000000000000002 ***\nas.factor(hour)22  0.2860782  0.0116010  24.660 < 0.0000000000000002 ***\nas.factor(hour)23  0.1313521  0.0116223  11.302 < 0.0000000000000002 ***\ndotw_simple2       0.0465693  0.0064074   7.268    0.000000000000365 ***\ndotw_simple3       0.0263717  0.0064389   4.096    0.000042094602228 ***\ndotw_simple4       0.0422632  0.0064500   6.552    0.000000000056646 ***\ndotw_simple5       0.0876232  0.0067093  13.060 < 0.0000000000000002 ***\ndotw_simple6       0.0063724  0.0068308   0.933                0.351    \ndotw_simple7      -0.0651120  0.0066560  -9.782 < 0.0000000000000002 ***\nTemperature       -0.0026108  0.0003125  -8.355 < 0.0000000000000002 ***\nPrecipitation     -0.4063579  0.0264563 -15.360 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.229 on 501509 degrees of freedom\nMultiple R-squared:  0.1062,\tAdjusted R-squared:  0.1062 \nF-statistic:  1923 on 31 and 501509 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n## Model 2: Add Temporal Lags\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel2 <- lm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +\n    lag1Hour + lag3Hours + lag1day,\n  data = train\n)\n\nsummary(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + \n    Precipitation + lag1Hour + lag3Hours + lag1day, data = train)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-8.1305 -0.4719 -0.1282  0.1603 17.3967 \n\nCoefficients:\n                    Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)        0.1932603  0.0222592   8.682 < 0.0000000000000002 ***\nas.factor(hour)1  -0.0107791  0.0100346  -1.074             0.282737    \nas.factor(hour)2  -0.0230237  0.0101934  -2.259             0.023902 *  \nas.factor(hour)3  -0.0418173  0.0101883  -4.104         0.0000405372 ***\nas.factor(hour)4  -0.0135448  0.0100669  -1.345             0.178474    \nas.factor(hour)5   0.0853365  0.0103467   8.248 < 0.0000000000000002 ***\nas.factor(hour)6   0.2572424  0.0101459  25.354 < 0.0000000000000002 ***\nas.factor(hour)7   0.3976395  0.0101391  39.219 < 0.0000000000000002 ***\nas.factor(hour)8   0.6977846  0.0101001  69.087 < 0.0000000000000002 ***\nas.factor(hour)9   0.2417010  0.0102189  23.652 < 0.0000000000000002 ***\nas.factor(hour)10  0.1866410  0.0101214  18.440 < 0.0000000000000002 ***\nas.factor(hour)11  0.2709541  0.0097863  27.687 < 0.0000000000000002 ***\nas.factor(hour)12  0.3363633  0.0099792  33.706 < 0.0000000000000002 ***\nas.factor(hour)13  0.3735371  0.0100963  36.997 < 0.0000000000000002 ***\nas.factor(hour)14  0.4308988  0.0099455  43.326 < 0.0000000000000002 ***\nas.factor(hour)15  0.5046635  0.0099906  50.514 < 0.0000000000000002 ***\nas.factor(hour)16  0.6477453  0.0102364  63.279 < 0.0000000000000002 ***\nas.factor(hour)17  0.8735161  0.0102958  84.842 < 0.0000000000000002 ***\nas.factor(hour)18  0.4671195  0.0103277  45.230 < 0.0000000000000002 ***\nas.factor(hour)19  0.3485184  0.0103319  33.732 < 0.0000000000000002 ***\nas.factor(hour)20  0.1725713  0.0102382  16.856 < 0.0000000000000002 ***\nas.factor(hour)21  0.1582020  0.0100713  15.708 < 0.0000000000000002 ***\nas.factor(hour)22  0.1177674  0.0098897  11.908 < 0.0000000000000002 ***\nas.factor(hour)23  0.0555991  0.0098945   5.619         0.0000000192 ***\ndotw_simple2       0.0187953  0.0054539   3.446             0.000569 ***\ndotw_simple3       0.0001545  0.0054807   0.028             0.977511    \ndotw_simple4       0.0125519  0.0054908   2.286             0.022255 *  \ndotw_simple5       0.0210761  0.0057149   3.688             0.000226 ***\ndotw_simple6      -0.0264412  0.0058176  -4.545         0.0000054930 ***\ndotw_simple7      -0.0480896  0.0056659  -8.488 < 0.0000000000000002 ***\nTemperature       -0.0029854  0.0002660 -11.222 < 0.0000000000000002 ***\nPrecipitation     -0.0757371  0.0225517  -3.358             0.000784 ***\nlag1Hour           0.4045613  0.0013124 308.268 < 0.0000000000000002 ***\nlag3Hours          0.1268892  0.0012904  98.337 < 0.0000000000000002 ***\nlag1day            0.1383590  0.0011966 115.623 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.046 on 501506 degrees of freedom\nMultiple R-squared:  0.3526,\tAdjusted R-squared:  0.3525 \nF-statistic:  8032 on 34 and 501506 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n## Model 3: Add Demographics\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntrain <- train %>%\n  mutate(\n    Med_Inc = coalesce(Med_Inc.x, Med_Inc.y),\n    Percent_Taking_Transit = coalesce(Percent_Taking_Transit.x, Percent_Taking_Transit.y),\n    Percent_White = coalesce(Percent_White.x, Percent_White.y)\n  )\n\nmodel3 <- lm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +\n    lag1Hour + lag3Hours + lag1day +\n    Med_Inc + Percent_Taking_Transit + Percent_White,\n  data = train\n)\n\nsummary(model3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + \n    Precipitation + lag1Hour + lag3Hours + lag1day + Med_Inc + \n    Percent_Taking_Transit + Percent_White, data = train)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-7.9347 -0.4856 -0.1343  0.2060 17.2849 \n\nCoefficients:\n                             Estimate     Std. Error t value\n(Intercept)             0.07035865497  0.02296933347   3.063\nas.factor(hour)1       -0.01263550808  0.00999293248  -1.264\nas.factor(hour)2       -0.02776401437  0.01015121714  -2.735\nas.factor(hour)3       -0.04817183994  0.01014641982  -4.748\nas.factor(hour)4       -0.02048830240  0.01002564380  -2.044\nas.factor(hour)5        0.07908923666  0.01030411404   7.676\nas.factor(hour)6        0.25339228067  0.01010388679  25.079\nas.factor(hour)7        0.39875573855  0.01009690120  39.493\nas.factor(hour)8        0.70588394474  0.01005881343  70.176\nas.factor(hour)9        0.25598622952  0.01017877653  25.149\nas.factor(hour)10       0.20073214358  0.01008168255  19.911\nas.factor(hour)11       0.28384981282  0.00974762163  29.120\nas.factor(hour)12       0.34945565388  0.00993976595  35.157\nas.factor(hour)13       0.38692281122  0.01005643789  38.475\nas.factor(hour)14       0.44397248351  0.00990618549  44.818\nas.factor(hour)15       0.51898813825  0.00995148772  52.152\nas.factor(hour)16       0.66562512447  0.01019751703  65.273\nas.factor(hour)17       0.89487190310  0.01025829554  87.234\nas.factor(hour)18       0.48980934212  0.01029071438  47.597\nas.factor(hour)19       0.36801774723  0.01029335492  35.753\nas.factor(hour)20       0.19178844146  0.01019993206  18.803\nas.factor(hour)21       0.17034684079  0.01003111238  16.982\nas.factor(hour)22       0.12549360840  0.00984930693  12.741\nas.factor(hour)23       0.05907603346  0.00985352962   5.995\ndotw_simple2            0.02023183401  0.00543127992   3.725\ndotw_simple3            0.00165536737  0.00545793226   0.303\ndotw_simple4            0.01433619693  0.00546800575   2.622\ndotw_simple5            0.02496157892  0.00569143075   4.386\ndotw_simple6           -0.02384996084  0.00579349646  -4.117\ndotw_simple7           -0.04836415603  0.00564234023  -8.572\nTemperature            -0.00292091392  0.00026492510 -11.025\nPrecipitation          -0.09084664977  0.02245911134  -4.045\nlag1Hour                0.39379990808  0.00131741309 298.919\nlag3Hours               0.11539088890  0.00129717196  88.956\nlag1day                 0.12631165617  0.00120607128 104.730\nMed_Inc                 0.00000118242  0.00000005558  21.273\nPercent_Taking_Transit -0.00246847307  0.00016925879 -14.584\nPercent_White           0.00174451828  0.00008498725  20.527\n                                   Pr(>|t|)    \n(Intercept)                        0.002190 ** \nas.factor(hour)1                   0.206071    \nas.factor(hour)2                   0.006237 ** \nas.factor(hour)3         0.0000020583139241 ***\nas.factor(hour)4                   0.040995 *  \nas.factor(hour)5         0.0000000000000165 ***\nas.factor(hour)6       < 0.0000000000000002 ***\nas.factor(hour)7       < 0.0000000000000002 ***\nas.factor(hour)8       < 0.0000000000000002 ***\nas.factor(hour)9       < 0.0000000000000002 ***\nas.factor(hour)10      < 0.0000000000000002 ***\nas.factor(hour)11      < 0.0000000000000002 ***\nas.factor(hour)12      < 0.0000000000000002 ***\nas.factor(hour)13      < 0.0000000000000002 ***\nas.factor(hour)14      < 0.0000000000000002 ***\nas.factor(hour)15      < 0.0000000000000002 ***\nas.factor(hour)16      < 0.0000000000000002 ***\nas.factor(hour)17      < 0.0000000000000002 ***\nas.factor(hour)18      < 0.0000000000000002 ***\nas.factor(hour)19      < 0.0000000000000002 ***\nas.factor(hour)20      < 0.0000000000000002 ***\nas.factor(hour)21      < 0.0000000000000002 ***\nas.factor(hour)22      < 0.0000000000000002 ***\nas.factor(hour)23        0.0000000020310006 ***\ndotw_simple2                       0.000195 ***\ndotw_simple3                       0.761665    \ndotw_simple4                       0.008746 ** \ndotw_simple5             0.0000115574245056 ***\ndotw_simple6             0.0000384433479579 ***\ndotw_simple7           < 0.0000000000000002 ***\nTemperature            < 0.0000000000000002 ***\nPrecipitation            0.0000523354751391 ***\nlag1Hour               < 0.0000000000000002 ***\nlag3Hours              < 0.0000000000000002 ***\nlag1day                < 0.0000000000000002 ***\nMed_Inc                < 0.0000000000000002 ***\nPercent_Taking_Transit < 0.0000000000000002 ***\nPercent_White          < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.042 on 501503 degrees of freedom\nMultiple R-squared:  0.3579,\tAdjusted R-squared:  0.3579 \nF-statistic:  7557 on 37 and 501503 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n## Model 4: Add Station Fixed Effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel4 <- lm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +\n    lag1Hour + lag3Hours + lag1day +\n    Med_Inc + Percent_Taking_Transit + Percent_White +\n    as.factor(start_station),\n  data = train\n)\n\n# Summary too long with all station dummies, just show key metrics\ncat(\"Model 4 R-squared:\", summary(model4)$r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 4 R-squared: 0.3835545 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Model 4 Adj R-squared:\", summary(model4)$adj.r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 4 Adj R-squared: 0.3831905 \n```\n\n\n:::\n:::\n\n\n## Model 5: Add Rush Hour Interaction\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel5 <- lm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +\n    lag1Hour + lag3Hours + lag1day + rush_hour + as.factor(month) +\n    Med_Inc + Percent_Taking_Transit + Percent_White +\n    as.factor(start_station) +\n    rush_hour * weekend,  # Rush hour effects different on weekends\n  data = train\n)\n\ncat(\"Model 5 R-squared:\", summary(model5)$r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 5 R-squared: 0.3868177 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Model 5 Adj R-squared:\", summary(model5)$adj.r.squared, \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nModel 5 Adj R-squared: 0.386452 \n```\n\n\n:::\n:::\n\n\n# MODEL EVALUATION\n\n## Calculate Predictions and MAE\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get predictions on test set\n\n# Create day of week factor with treatment (dummy) coding\ntest <- test %>%\n  mutate(dotw_simple = factor(dotw, levels = c(\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\")))\n\ntest <- test %>%\n  mutate(\n    Med_Inc = coalesce(Med_Inc.x, Med_Inc.y),\n    Percent_Taking_Transit = coalesce(Percent_Taking_Transit.x, Percent_Taking_Transit.y),\n    Percent_White = coalesce(Percent_White.x, Percent_White.y)\n  )\n# Set contrasts to treatment coding (dummy variables)\ncontrasts(test$dotw_simple) <- contr.treatment(7)\n\ntest <- test %>%\n  mutate(\n    pred1 = predict(model1, newdata = test),\n    pred2 = predict(model2, newdata = test),\n    pred3 = predict(model3, newdata = test),\n    pred4 = predict(model4, newdata = test),\n    pred5 = predict(model5, newdata = test)\n  )\n\n# Calculate MAE for each model\nmae_results <- data.frame(\n  Model = c(\n    \"1. Time + Weather\",\n    \"2. + Temporal Lags\",\n    \"3. + Demographics\",\n    \"4. + Station FE\",\n    \"5. + Rush Hour Interaction\"\n  ),\n  MAE = c(\n    mean(abs(test$Trip_Count - test$pred1), na.rm = TRUE),\n    mean(abs(test$Trip_Count - test$pred2), na.rm = TRUE),\n    mean(abs(test$Trip_Count - test$pred3), na.rm = TRUE),\n    mean(abs(test$Trip_Count - test$pred4), na.rm = TRUE),\n    mean(abs(test$Trip_Count - test$pred5), na.rm = TRUE)\n  )\n)\n\nkable(mae_results, \n      digits = 2,\n      caption = \"Mean Absolute Error by Model (Test Set)\",\n      col.names = c(\"Model\", \"MAE (trips)\")) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Mean Absolute Error by Model (Test Set)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Model </th>\n   <th style=\"text-align:right;\"> MAE (trips) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 1. Time + Weather </td>\n   <td style=\"text-align:right;\"> 0.84 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 2. + Temporal Lags </td>\n   <td style=\"text-align:right;\"> 0.71 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 3. + Demographics </td>\n   <td style=\"text-align:right;\"> 0.71 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 4. + Station FE </td>\n   <td style=\"text-align:right;\"> 0.71 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 5. + Rush Hour Interaction </td>\n   <td style=\"text-align:right;\"> 0.71 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Visualize Model Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(mae_results, aes(x = reorder(Model, -MAE), y = MAE)) +\n  geom_col(fill = \"#3182bd\", alpha = 0.8) +\n  geom_text(aes(label = round(MAE, 2)), vjust = -0.5) +\n  labs(\n    title = \"Model Performance Comparison\",\n    subtitle = \"Lower MAE = Better Predictions\",\n    x = \"Model\",\n    y = \"Mean Absolute Error (trips)\"\n  ) +\n  plotTheme +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](lab5_files/figure-html/compare_models-1.png){width=672}\n:::\n:::\n\n\n# Compare Results to Q1 2025\n\n## MAE Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## MAE comparison\nq1_mae <- c(0.60, 0.50, 0.74, 0.73, 0.73) ## Matrics from in-class exercise\n\nmae_compare <- data.frame(\n  Model  = mae_results$Model,\n  Q1_MAE = q1_mae,\n  Q3_MAE = mae_results$MAE   \n)\n\nkable(\n  mae_compare,\n  digits  = 2,\n  caption = \"Mean Absolute Error by Model: Q1 vs Q3 (Test Set)\",\n  col.names = c(\"Model\", \"Q1_MAE (trips)\", \"Q3_MAE (trips)\")\n) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Mean Absolute Error by Model: Q1 vs Q3 (Test Set)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Model </th>\n   <th style=\"text-align:right;\"> Q1_MAE (trips) </th>\n   <th style=\"text-align:right;\"> Q3_MAE (trips) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 1. Time + Weather </td>\n   <td style=\"text-align:right;\"> 0.60 </td>\n   <td style=\"text-align:right;\"> 0.84 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 2. + Temporal Lags </td>\n   <td style=\"text-align:right;\"> 0.50 </td>\n   <td style=\"text-align:right;\"> 0.71 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 3. + Demographics </td>\n   <td style=\"text-align:right;\"> 0.74 </td>\n   <td style=\"text-align:right;\"> 0.71 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 4. + Station FE </td>\n   <td style=\"text-align:right;\"> 0.73 </td>\n   <td style=\"text-align:right;\"> 0.71 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> 5. + Rush Hour Interaction </td>\n   <td style=\"text-align:right;\"> 0.73 </td>\n   <td style=\"text-align:right;\"> 0.71 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nOverall, Model 2, which adds temporal lags, performs best because it has the lowest MAE in Q1 and remains tied for the lowest MAE in Q3. Model 1 has the highest error in both quarters, showing that time and weather alone are less effective at predicting ridership. The results also show that errors are generally higher in Q3 than in Q1, suggesting that summer bike-share demand is harder to predict than winter demand. This likely reflects greater variability in summer travel behavior, while the strong performance of Model 2 suggests that recent trip patterns remain one of the most useful predictors across seasons.\n\n## Temporal Patterns Comparison (summer vs. winter)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Comparison between Q1 2025 and Q3 2024 (summer vs. winter)\nlibrary(ggplot2)\nlibrary(png)\nlibrary(grid)\nlibrary(cowplot)\n\nimg1 <- png::readPNG(\"data/daily_ridership_Q3.png\")\np_left <- grid::rasterGrob(img1, interpolate = TRUE)\n\nimg2 <- png::readPNG(\"data/daily_ridership_Q1.png\")  \np_right <- grid::rasterGrob(img2, interpolate = TRUE)\n\ncowplot::plot_grid(\n  p_left,\n  p_right,\n  labels = c(\"summer vs. winter\"),\n  ncol = 2\n)\n```\n\n::: {.cell-output-display}\n![](lab5_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n:::\n\n\nSummer and winter show clearly different temporal ridership patterns. In summer, daily trips stay consistently high, with strong weekday–weekend fluctuations and a pattern that rises through mid-season before gradually declining toward October. In contrast, winter begins at much lower levels and shows a steady upward trend as temperatures warm, with ridership recovering from January lows and climbing sharply into March and April. Overall, summer displays high, stable, and highly active demand, while winter reflects low but steadily increasing activity, capturing a clear seasonal effect in bike-share usage.\n\n## Important Features\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Use partial R square to determine the  most important feature\nlibrary(rsq)\nrsq.partial(model2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$adjustment\n[1] FALSE\n\n$variable\n[1] \"as.factor(hour)\" \"dotw_simple\"     \"Temperature\"     \"Precipitation\"  \n[5] \"lag1Hour\"        \"lag3Hours\"       \"lag1day\"        \n\n$partial.rsq\n[1] 0.04559664069 0.00048407188 0.00025104419 0.00002248911 0.15930182252\n[6] 0.01891740820 0.02596483603\n```\n\n\n:::\n:::\n\n\nIn both Q1 and Q3, the one-hour lag (lag1Hour) is by far the most important predictor, followed by hour-of-day and the one-day lag. Weather and day-of-week contribute very little once temporal patterns and lags are included, and their independent explanatory power is even smaller in Q3.\n\n# SPACE-TIME ERROR ANALYSIS\n\n## Observed vs. Predicted\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest <- test %>%\n  mutate(\n    error = Trip_Count - pred2,            #best result model (change if ness)\n    abs_error = abs(error),\n    time_of_day = case_when(\n      hour < 7 ~ \"Overnight\",\n      hour >= 7 & hour < 10 ~ \"AM Rush\",\n      hour >= 10 & hour < 15 ~ \"Mid-Day\",\n      hour >= 15 & hour <= 18 ~ \"PM Rush\",\n      hour > 18 ~ \"Evening\"\n    )\n  )\n\n# Scatter plot by time and day type\nggplot(test, aes(x = Trip_Count, y = pred2)) +\n  geom_point(alpha = 0.2, color = \"#3182bd\") +\n  geom_abline(slope = 1, intercept = 0, color = \"red\", linewidth = 1) +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"darkgreen\") +\n  facet_grid(weekend ~ time_of_day) +\n  labs(\n    title = \"Observed vs. Predicted Bike Trips\",\n    subtitle = \"Model 2 performance by time period\",\n    x = \"Observed Trips\",\n    y = \"Predicted Trips\",\n    caption = \"Red line = perfect predictions; Green line = actual model fit\"\n  ) +\n  plotTheme\n```\n\n::: {.cell-output-display}\n![](lab5_files/figure-html/obs_vs_pred-1.png){width=672}\n:::\n:::\n\n\n## Spatial Error Patterns\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate MAE by station\nstation_errors <- test %>%\n  group_by(start_station, start_lat.x, start_lon.y) %>%\n  summarize(\n    MAE = mean(abs_error, na.rm = TRUE),\n    avg_demand = mean(Trip_Count, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  filter(!is.na(start_lat.x), !is.na(start_lon.y))\n\n## Create Two Maps Side-by-Side with Proper Legends (sorry these maps are ugly)\n\n# Calculate station errors\nstation_errors <- test %>%\n  filter(!is.na(pred2)) %>%\n  group_by(start_station, start_lat.x, start_lon.y) %>%\n  summarize(\n    MAE = mean(abs(Trip_Count - pred2), na.rm = TRUE),\n    avg_demand = mean(Trip_Count, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  filter(!is.na(start_lat.x), !is.na(start_lon.y))\n\n# Map 1: Prediction Errors\np1 <- ggplot() +\n  geom_sf(data = philly_census, fill = \"grey95\", color = \"white\", size = 0.1) +\n  geom_point(\n    data = station_errors,\n    aes(x = start_lon.y, y = start_lat.x, color = MAE),\n    size = 0.8,\n    alpha = 0.7\n  ) +\n  scale_color_viridis(\n    option = \"plasma\",\n    name = \"MAE (trips)\",\n    direction = -1,\n    breaks = c(0.5, 1.0, 1.5),\n    labels = c(\"0.5\", \"1.0\", \"1.5\")\n  ) +\n  labs(title = \"Prediction Errors\") +\n  mapTheme +\n  theme(\n    legend.position = \"bottom\",\n    legend.title = element_text(size = 10, face = \"bold\"),\n    legend.text = element_text(size = 9),\n    plot.title = element_text(size = 14, face = \"bold\", hjust = 0.5)\n  ) +\n  guides(color = guide_colorbar(\n    barwidth = 12,\n    barheight = 1,\n    title.position = \"top\",\n    title.hjust = 0.5\n  ))\n\n# Map 2: Average Demand  \np2 <- ggplot() +\n  geom_sf(data = philly_census, fill = \"grey95\", color = \"white\", size = 0.1) +\n  geom_point(\n    data = station_errors,\n    aes(x = start_lon.y, y = start_lat.x, color = avg_demand),\n    size = 0.8,\n    alpha = 0.7\n  ) +\n  scale_color_viridis(\n    option = \"viridis\",\n    name = \"Avg Demand (trips/hour)\",\n    direction = -1,\n    breaks = c(0.5, 1.0, 1.5, 2.0, 2.5),\n    labels = c(\"0.5\", \"1.0\", \"1.5\", \"2.0\", \"2.5\")\n  ) +\n  labs(title = \"Average Demand\") +\n  mapTheme +\n  theme(\n    legend.position = \"bottom\",\n    legend.title = element_text(size = 10, face = \"bold\"),\n    legend.text = element_text(size = 9),\n    plot.title = element_text(size = 14, face = \"bold\", hjust = 0.5)\n  ) +\n  guides(color = guide_colorbar(\n    barwidth = 12,\n    barheight = 1,\n    title.position = \"top\",\n    title.hjust = 0.5\n  ))\n\nlibrary(gridExtra)\n\n# Combine\ngrid.arrange(\n  p1, p2,\n  ncol = 2\n  )\n```\n\n::: {.cell-output-display}\n![](lab5_files/figure-html/spatial_errors-1.png){width=672}\n:::\n:::\n\n\n## Temporal Error Patterns\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# MAE by time of day and day type\ntemporal_errors <- test %>%\n  group_by(time_of_day, weekend) %>%\n  summarize(\n    MAE = mean(abs_error, na.rm = TRUE),\n    .groups = \"drop\"\n  ) %>%\n  mutate(day_type = ifelse(weekend == 1, \"Weekend\", \"Weekday\"))\n\nggplot(temporal_errors, aes(x = time_of_day, y = MAE, fill = day_type)) +\n  geom_col(position = \"dodge\") +\n  scale_fill_manual(values = c(\"Weekday\" = \"#08519c\", \"Weekend\" = \"#6baed6\")) +\n  labs(\n    title = \"Prediction Errors by Time Period\",\n    subtitle = \"When is the model struggling most?\",\n    x = \"Time of Day\",\n    y = \"Mean Absolute Error (trips)\",\n    fill = \"Day Type\"\n  ) +\n  plotTheme +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n\n::: {.cell-output-display}\n![](lab5_files/figure-html/temporal_errors-1.png){width=672}\n:::\n:::\n\n\n## Errors and Demographics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join demographic data to station errors\nstation_errors_demo <- station_errors %>%\n  left_join(\n    station_attributes %>% select(start_station, Med_Inc, Percent_Taking_Transit, Percent_White),\n    by = \"start_station\"\n  ) %>%\n  filter(!is.na(Med_Inc))\n\n# Create plots\np1 <- ggplot(station_errors_demo, aes(x = Med_Inc, y = MAE)) +\n  geom_point(alpha = 0.5, color = \"#3182bd\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\") +\n  scale_x_continuous(labels = scales::dollar) +\n  labs(title = \"Errors vs. Median Income\", x = \"Median Income\", y = \"MAE\") +\n  plotTheme\n\np2 <- ggplot(station_errors_demo, aes(x = Percent_Taking_Transit, y = MAE)) +\n  geom_point(alpha = 0.5, color = \"#3182bd\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\") +\n  labs(title = \"Errors vs. Transit Usage\", x = \"% Taking Transit\", y = \"MAE\") +\n  plotTheme\n\np3 <- ggplot(station_errors_demo, aes(x = Percent_White, y = MAE)) +\n  geom_point(alpha = 0.5, color = \"#3182bd\") +\n  geom_smooth(method = \"lm\", se = FALSE, color = \"red\") +\n  labs(title = \"Errors vs. Race\", x = \"% White\", y = \"MAE\") +\n  plotTheme\n\n(p1 | p2) / (p3 | plot_spacer())\n```\n\n::: {.cell-output-display}\n![](lab5_files/figure-html/errors_demographics-1.png){width=672}\n:::\n:::\n\n\nErrors tend to be slightly higher in higher-income and higher-percent-White neighborhoods, while they are lower in areas with high transit usage. This suggests the model struggles more in wealthier, less transit-oriented areas. The equity implication is that model performance is not uniform—some communities may receive less accurate predictions than others, which could affect planning decisions if not addressed.\n\n# Feature Engineering\n\n## Spatial features\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(geosphere)\n\n## Distance to Center City\n\n# Center City coordinate (Use Philadelphia City Hall)\ncenter_lat <- 39.952800\ncenter_lon <- -75.163500\n\n# Calculate distance in kilometers\nstudy_panel_complete <- study_panel_complete %>%\n  mutate(\n    dist_to_center = distHaversine(\n      cbind(start_lon.y, start_lat.y),\n      cbind(center_lon, center_lat)\n    ) / 1000  # convert meters to km\n  )\n```\n:::\n\n\n## Trip history features\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Rolling 7-day average demand\nlibrary(slider)\n\nstudy_panel_complete <- study_panel_complete %>%\n  arrange(start_station, date, hour) %>%\n  group_by(start_station) %>%\n  mutate(\n    rolling7 = slide_dbl(\n      Trip_Count,\n      mean,\n      .before = 168,\n      .complete = TRUE\n    )\n  ) %>%\n  ungroup()\n```\n:::\n\n\n## Split train/test Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Which stations have trips in BOTH early and late periods?\nearly_stations <- study_panel_complete %>%\n  filter(week < 36) %>%\n  filter(Trip_Count > 0) %>%\n  distinct(start_station) %>%\n  pull(start_station)\n\nlate_stations <- study_panel_complete %>%\n  filter(week >= 36) %>%\n  filter(Trip_Count > 0) %>%\n  distinct(start_station) %>%\n  pull(start_station)\n\n# Keep only stations that appear in BOTH periods\ncommon_stations <- intersect(early_stations, late_stations)\n\n\n# Filter panel to only common stations\nstudy_panel_complete <- study_panel_complete %>%\n  filter(start_station %in% common_stations)\n\n# NOW create train/test split\ntrain <- study_panel_complete %>%\n  filter(week < 36)\n\ntest <- study_panel_complete %>%\n  filter(week >= 36)\n\ncat(\"Training observations:\", format(nrow(train), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining observations: 501,541 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Testing observations:\", format(nrow(test), big.mark = \",\"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTesting observations: 207,244 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Training date range:\", min(train$date), \"to\", max(train$date), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTraining date range: 20270 to 20333 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Testing date range:\", min(test$date), \"to\", max(test$date), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTesting date range: 20334 to 20361 \n```\n\n\n:::\n:::\n\n\n## Add two new presictors into the best model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create day of week factor with treatment (dummy) coding\ntrain <- train %>%\n  mutate(dotw_simple = factor(dotw, levels = c(\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\")))\n\n# Set contrasts to treatment coding (dummy variables)\ncontrasts(train$dotw_simple) <- contr.treatment(7)\n\nmodel_n <- lm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +\n    lag1Hour + lag3Hours + lag1day + dist_to_center + rolling7,\n  data = train\n)\n\nsummary(model_n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + \n    Precipitation + lag1Hour + lag3Hours + lag1day + dist_to_center + \n    rolling7, data = train)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-6.9299 -0.5079 -0.1184  0.2803 17.6736 \n\nCoefficients:\n                    Estimate Std. Error t value             Pr(>|t|)    \n(Intercept)       -0.2646910  0.0233566 -11.333 < 0.0000000000000002 ***\nas.factor(hour)1  -0.0215583  0.0105788  -2.038             0.041562 *  \nas.factor(hour)2  -0.0468092  0.0106622  -4.390  0.00001132766890489 ***\nas.factor(hour)3  -0.0666273  0.0106586  -6.251  0.00000000040806655 ***\nas.factor(hour)4  -0.0353589  0.0104881  -3.371             0.000748 ***\nas.factor(hour)5   0.0673682  0.0107866   6.246  0.00000000042271421 ***\nas.factor(hour)6   0.2587318  0.0105329  24.564 < 0.0000000000000002 ***\nas.factor(hour)7   0.4356190  0.0105591  41.255 < 0.0000000000000002 ***\nas.factor(hour)8   0.7787979  0.0105195  74.034 < 0.0000000000000002 ***\nas.factor(hour)9   0.3600817  0.0106951  33.668 < 0.0000000000000002 ***\nas.factor(hour)10  0.2885503  0.0105564  27.334 < 0.0000000000000002 ***\nas.factor(hour)11  0.3687875  0.0102336  36.037 < 0.0000000000000002 ***\nas.factor(hour)12  0.4246509  0.0104091  40.796 < 0.0000000000000002 ***\nas.factor(hour)13  0.4644507  0.0105663  43.956 < 0.0000000000000002 ***\nas.factor(hour)14  0.5169114  0.0104380  49.522 < 0.0000000000000002 ***\nas.factor(hour)15  0.5954390  0.0105133  56.637 < 0.0000000000000002 ***\nas.factor(hour)16  0.7673669  0.0106708  71.913 < 0.0000000000000002 ***\nas.factor(hour)17  1.0273652  0.0108907  94.334 < 0.0000000000000002 ***\nas.factor(hour)18  0.6105871  0.0108756  56.143 < 0.0000000000000002 ***\nas.factor(hour)19  0.4767052  0.0109722  43.447 < 0.0000000000000002 ***\nas.factor(hour)20  0.2813512  0.0108853  25.847 < 0.0000000000000002 ***\nas.factor(hour)21  0.2174694  0.0105602  20.593 < 0.0000000000000002 ***\nas.factor(hour)22  0.1605793  0.0104308  15.395 < 0.0000000000000002 ***\nas.factor(hour)23  0.0739143  0.0104373   7.082  0.00000000000142521 ***\ndotw_simple2       0.0575659  0.0055434  10.385 < 0.0000000000000002 ***\ndotw_simple3       0.0161450  0.0055902   2.888             0.003876 ** \ndotw_simple4       0.0360255  0.0055350   6.509  0.00000000007587620 ***\ndotw_simple5       0.0463412  0.0058387   7.937  0.00000000000000208 ***\ndotw_simple6      -0.0197771  0.0058929  -3.356             0.000791 ***\ndotw_simple7      -0.0614182  0.0055898 -10.988 < 0.0000000000000002 ***\nTemperature       -0.0006399  0.0002692  -2.377             0.017439 *  \nPrecipitation     -0.0857631  0.0225474  -3.804             0.000143 ***\nlag1Hour           0.3346474  0.0014081 237.659 < 0.0000000000000002 ***\nlag3Hours          0.0536807  0.0013994  38.361 < 0.0000000000000002 ***\nlag1day            0.0682287  0.0013108  52.051 < 0.0000000000000002 ***\ndist_to_center    -0.0042454  0.0010508  -4.040  0.00005344060129632 ***\nrolling7           0.5257068  0.0041081 127.969 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.029 on 457320 degrees of freedom\n  (44184 observations deleted due to missingness)\nMultiple R-squared:  0.3849,\tAdjusted R-squared:  0.3849 \nF-statistic:  7951 on 36 and 457320 DF,  p-value: < 0.00000000000000022\n```\n\n\n:::\n:::\n\n\n## New Model Evaluation and MAE\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get predictions on test set\n\n# Create day of week factor with treatment (dummy) coding\ntest <- test %>%\n  mutate(dotw_simple = factor(dotw, levels = c(\"Mon\", \"Tue\", \"Wed\", \"Thu\", \"Fri\", \"Sat\", \"Sun\")))\n\n# Set contrasts to treatment coding (dummy variables)\ncontrasts(test$dotw_simple) <- contr.treatment(7)\n\ntest <- test %>%\n  mutate(\n    pred_n = predict(model_n, newdata = test)\n  )\n\n# Calculate MAE for each model\nmae_results_new <- data.frame(\n  Model = c(\n    \"2. + Temporal Lags\",\n    \"New Model. + Rolling 7-day average demand and Distance to Center City\",\n    \"New Poisson Model\"\n  ),\n  MAE = c(\n    mean(abs(test$Trip_Count - test$pred2), na.rm = TRUE),\n    mean(abs(test$Trip_Count - test$pred_n), na.rm = TRUE),\n    mean(abs(test$Trip_Count - test$pred_pois), na.rm = TRUE)\n  ),\n   RMSE = c(\n    sqrt(mean((test$Trip_Count - test$pred2)^2,  na.rm = TRUE)),\n    sqrt(mean((test$Trip_Count - test$pred_n)^2, na.rm = TRUE)),\n    sqrt(mean((test$Trip_Count - test$pred_pois)^2, na.rm = TRUE))\n  )\n)\n\nkable(mae_results_new, \n      digits = 5,\n      caption = \"Mean Absolute Error by Model (Test Set)\",\n      col.names = c(\"Model\", \"MAE (trips)\", \"RMSE (trips)\")) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Mean Absolute Error by Model (Test Set)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Model </th>\n   <th style=\"text-align:right;\"> MAE (trips) </th>\n   <th style=\"text-align:right;\"> RMSE (trips) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 2. + Temporal Lags </td>\n   <td style=\"text-align:right;\"> NaN </td>\n   <td style=\"text-align:right;\"> NaN </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> New Model. + Rolling 7-day average demand and Distance to Center City </td>\n   <td style=\"text-align:right;\"> 0.71904 </td>\n   <td style=\"text-align:right;\"> 1.12527 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> New Poisson Model </td>\n   <td style=\"text-align:right;\"> NaN </td>\n   <td style=\"text-align:right;\"> NaN </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\nThe two new models perform similarly, while the Temporal Lags model cannot be evaluated because its MAE and RMSE are NaN. Of the valid models, the New Poisson Model has the lower MAE, so it is slightly better on average, while the rolling 7-day average model has the lower RMSE, suggesting more stable predictions with fewer large errors.\n\n## Poisson model\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Train a poisson model\nmodel_poisson <- glm(\n  Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + Precipitation +\n    lag1Hour + lag3Hours + lag1day + dist_to_center + rolling7,\n  family = poisson(link = \"log\"),\n  data   = train\n)\n\nsummary(model_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = Trip_Count ~ as.factor(hour) + dotw_simple + Temperature + \n    Precipitation + lag1Hour + lag3Hours + lag1day + dist_to_center + \n    rolling7, family = poisson(link = \"log\"), data = train)\n\nCoefficients:\n                      Estimate   Std. Error  z value             Pr(>|z|)    \n(Intercept)       -1.597467267  0.028671578  -55.716 < 0.0000000000000002 ***\nas.factor(hour)1  -0.297839161  0.023656495  -12.590 < 0.0000000000000002 ***\nas.factor(hour)2  -0.703090169  0.027176906  -25.871 < 0.0000000000000002 ***\nas.factor(hour)3  -1.282650758  0.033924069  -37.809 < 0.0000000000000002 ***\nas.factor(hour)4  -1.077887323  0.030691237  -35.120 < 0.0000000000000002 ***\nas.factor(hour)5  -0.127736134  0.023033554   -5.546         0.0000000293 ***\nas.factor(hour)6   0.670210064  0.018691904   35.856 < 0.0000000000000002 ***\nas.factor(hour)7   1.105948527  0.017382196   63.625 < 0.0000000000000002 ***\nas.factor(hour)8   1.537352832  0.016474887   93.315 < 0.0000000000000002 ***\nas.factor(hour)9   1.153985656  0.017059476   67.645 < 0.0000000000000002 ***\nas.factor(hour)10  1.033953542  0.017297023   59.776 < 0.0000000000000002 ***\nas.factor(hour)11  1.116417738  0.016942989   65.893 < 0.0000000000000002 ***\nas.factor(hour)12  1.193333179  0.016894954   70.633 < 0.0000000000000002 ***\nas.factor(hour)13  1.243489696  0.016875262   73.687 < 0.0000000000000002 ***\nas.factor(hour)14  1.302069360  0.016687381   78.027 < 0.0000000000000002 ***\nas.factor(hour)15  1.388750233  0.016583110   83.745 < 0.0000000000000002 ***\nas.factor(hour)16  1.527543423  0.016440056   92.916 < 0.0000000000000002 ***\nas.factor(hour)17  1.674794784  0.016313994  102.660 < 0.0000000000000002 ***\nas.factor(hour)18  1.370316653  0.016669500   82.205 < 0.0000000000000002 ***\nas.factor(hour)19  1.279863318  0.016901594   75.724 < 0.0000000000000002 ***\nas.factor(hour)20  1.048668843  0.017370716   60.370 < 0.0000000000000002 ***\nas.factor(hour)21  0.896386343  0.017567283   51.026 < 0.0000000000000002 ***\nas.factor(hour)22  0.725936816  0.018094248   40.120 < 0.0000000000000002 ***\nas.factor(hour)23  0.397661117  0.019247374   20.661 < 0.0000000000000002 ***\ndotw_simple2       0.088399022  0.006398730   13.815 < 0.0000000000000002 ***\ndotw_simple3       0.017801061  0.006537671    2.723              0.00647 ** \ndotw_simple4       0.056206234  0.006486085    8.666 < 0.0000000000000002 ***\ndotw_simple5       0.098473411  0.006721049   14.651 < 0.0000000000000002 ***\ndotw_simple6       0.000001129  0.006924753    0.000              0.99987    \ndotw_simple7      -0.089631398  0.006807574  -13.166 < 0.0000000000000002 ***\nTemperature       -0.000549945  0.000296382   -1.856              0.06352 .  \nPrecipitation     -1.000017321  0.055777627  -17.929 < 0.0000000000000002 ***\nlag1Hour           0.129445057  0.000896418  144.403 < 0.0000000000000002 ***\nlag3Hours          0.017797063  0.001083996   16.418 < 0.0000000000000002 ***\nlag1day            0.020071443  0.000987413   20.327 < 0.0000000000000002 ***\ndist_to_center    -0.169607202  0.001522073 -111.432 < 0.0000000000000002 ***\nrolling7           0.540747606  0.003586507  150.773 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 810357  on 457356  degrees of freedom\nResidual deviance: 478516  on 457320  degrees of freedom\n  (44184 observations deleted due to missingness)\nAIC: 876846\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate dispersion parameter\ndispersion <- sum(residuals(model_poisson, type = \"pearson\")^2) / \n              model_poisson$df.residual\n\ncat(\"Dispersion parameter:\", round(dispersion, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDispersion parameter: 1.31 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncat(\"Rule of thumb: >1.5 suggests overdispersion\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRule of thumb: >1.5 suggests overdispersion\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nif (dispersion > 1.5) {\n  cat(\"⚠ Overdispersion detected! Consider Negative Binomial model.\\n\")\n} else {\n  cat(\"✓ Dispersion looks okay for Poisson model.\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Dispersion looks okay for Poisson model.\n```\n\n\n:::\n:::\n\n\n## Evaluation of Poisson Model (MAE and RMSE)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest <- test %>%\n  mutate(\n    pred_pois = predict(model_poisson, newdata = test, type = \"response\")\n  )\n\n# Calculate MAE for each model\nmae_results_nn <- data.frame(\n  Model = c(\n    \"2. + Temporal Lags\",\n    \"New Model. + Rolling 7-day average demand and Distance to Center City\",\n    \"New Poisson Model\"\n  ),\n  MAE = c(\n    mean(abs(test$Trip_Count - test$pred2), na.rm = TRUE),\n    mean(abs(test$Trip_Count - test$pred_n), na.rm = TRUE),\n    mean(abs(test$Trip_Count - test$pred_pois), na.rm = TRUE)\n  ),\n   RMSE = c(\n    sqrt(mean((test$Trip_Count - test$pred2)^2,  na.rm = TRUE)),\n    sqrt(mean((test$Trip_Count - test$pred_n)^2, na.rm = TRUE)),\n    sqrt(mean((test$Trip_Count - test$pred_pois)^2, na.rm = TRUE))\n  )\n)\n\nkable(mae_results_nn, \n      digits = 5,\n      caption = \"Mean Absolute Error by Model (Test Set)\",\n      col.names = c(\"Model\", \"MAE (trips)\", \"RMSE (trips)\")) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\"))\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Mean Absolute Error by Model (Test Set)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Model </th>\n   <th style=\"text-align:right;\"> MAE (trips) </th>\n   <th style=\"text-align:right;\"> RMSE (trips) </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> 2. + Temporal Lags </td>\n   <td style=\"text-align:right;\"> NaN </td>\n   <td style=\"text-align:right;\"> NaN </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> New Model. + Rolling 7-day average demand and Distance to Center City </td>\n   <td style=\"text-align:right;\"> 0.71904 </td>\n   <td style=\"text-align:right;\"> 1.12527 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> New Poisson Model </td>\n   <td style=\"text-align:right;\"> 0.70658 </td>\n   <td style=\"text-align:right;\"> 1.26648 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\nBetween the two valid models, the New Poisson Model has the lower MAE, so it performs slightly better on average, while the rolling 7-day average model has the lower RMSE, suggesting fewer large prediction errors. Overall, the Poisson model is slightly better in average accuracy, but the rolling-average model appears more stable.\n\n# Critical Reflection\n\nOverall, the final model performance is reasonably strong, with MAE values generally below 1 trip, but the remaining error is still meaningful enough that Indego should be cautious about relying on the model alone for operational decisions. Across our results, adding temporal lags clearly improved prediction accuracy, and the newer models with rolling demand and Poisson specification performed competitively, with the Poisson model showing slightly better average accuracy and the rolling-average model appearing somewhat more stable against larger errors. At the same time, the model comparisons suggest that bike-share demand remains harder to predict in higher-demand periods, especially in summer, when ridership is more variable. In practice, this means the model is useful as a decision-support tool for identifying broad demand patterns and guiding planning priorities, but it should not be treated as the sole basis for real-time rebalancing or hourly truck dispatch. Live system monitoring, staff judgment, and awareness of unusual conditions should still play an important role.\n\nThe analysis also shows that the model cannot fully capture all sources of variation in ridership. Factors such as holidays, special events, sudden weather shifts, and other short-term disruptions are only partially reflected in the current specification, even after adding weather, lags, and demographic variables. The seasonal comparison also suggests that relationships are not equally stable across time, since prediction error tends to rise in Q3 relative to Q1. With more time and data, the model could be improved by adding richer temporal and spatial predictors, such as event calendars, more detailed built-environment and transit accessibility measures, longer ridership histories, and possibly more flexible modeling approaches that can better capture nonlinear or changing demand patterns.\n\nFrom an equity perspective, these modeling limits matter because prediction errors are not just statistical problems; they can translate into uneven service quality across places and groups of riders. If the model is less accurate in high-demand or highly variable areas, then relying too heavily on it could unintentionally reinforce service gaps by sending too few bikes where demand is strongest or by misallocating resources across neighborhoods. To reduce this risk, Indego should regularly evaluate model performance across different station areas and community contexts, not just overall accuracy. Any operational use of the model should also be paired with equity goals, such as minimum service standards or explicit checks on whether prediction errors are disproportionately affecting particular neighborhoods. Used this way, the model can support more efficient planning while still protecting fair access to the bike-share system.\n",
    "supporting": [
      "lab5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}