{
  "hash": "e6f0ffe3bab450513968cd6d3d36ea1c",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 2: Spatial Analysis and Visualization\"\nsubtitle: \"Healthcare Access and Equity in Pennsylvania\"\nauthor: \"Coco Zhou\"\ndate: February 17, 2026\nformat: \n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n## Assignment Overview\n\n**Learning Objectives:**\n- Apply spatial operations to answer policy-relevant research questions\n- Integrate census demographic data with spatial analysis\n- Create publication-quality visualizations and maps\n- Work with spatial data from multiple sources\n- Communicate findings effectively for policy audiences\n\n---\n\n## Part 1: Healthcare Access for Vulnerable Populations\n\n### Research Question\n\n**Which Pennsylvania counties have the highest proportion of vulnerable populations (elderly + low-income) living far from hospitals?**\n\nYour analysis should identify counties that should be priorities for healthcare investment and policy intervention.\n\n### Required Analysis Steps\n\nComplete the following analysis, documenting each step with code and brief explanations:\n\n#### Step 1: Data Collection (5 points)\n\nLoad the required spatial data:\n- Pennsylvania county boundaries\n- Pennsylvania hospitals (from lecture data)\n- Pennsylvania census tracts\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(sf)\nlibrary(tidyverse)\nlibrary(tigris)\nlibrary(tidycensus)\nlibrary(scales)\nlibrary(patchwork)\nlibrary(here)\n\n# Load spatial data\npa_counties <- st_read(\"data/Pennsylvania_County_Boundaries.shp\")\ndistricts <- st_read(\"data/districts.geojson\")\nhospitals <- st_read(\"data/hospitals.geojson\")\ncensus_tracts <- st_read (\"data/PA_Census_Tracts_2020.geojson\")\n\n# Check that all data loaded correctly\nst_crs(counties)\n\nnrow(hospitals)  \nst_crs(hospitals)\n\nnrow(tracts)    \nst_crs(tracts) \n```\n:::\n\n\n**Questions to answer:**\n- How many hospitals are in your dataset?\n223 hospitals\n- How many census tracts?\n3445 census tracts\n- What coordinate reference system is each dataset in?\nEPSG:4326 (WGS 84)\n\n---\n\n#### Step 2: Get Demographic Data \n\nUse `tidycensus` to download tract-level demographic data for Pennsylvania.\n\n**Required variables:**\n- Total population\n- Median household income\n- Population 65 years and over (you may need to sum multiple age categories)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get demographic data from ACS\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(sf)\n\nmale_65_vars   <- paste0(\"B01001_0\", 20:25)\nfemale_65_vars <- paste0(\"B01001_0\", 44:49)\nvars_65 <- c(male_65_vars, female_65_vars)\n\nvars_65_named <- setNames(vars_65, vars_65)\n\nacs_pa_long <- get_acs(\n  geography = \"tract\",\n  state = \"PA\",\n  year = 2024,\n  survey = \"acs5\",\n  variables = c(\n    total_pop = \"B01003_001\",\n    med_income = \"B19013_001\",\n    vars_65_named\n  ),\n  geometry = FALSE,\n  cache_table = TRUE\n)\n\n# Join to tract boundaries\nacs_pa <- acs_pa_long %>%\n  select(GEOID, NAME, variable, estimate) %>%\n  pivot_wider(names_from = variable, values_from = estimate) %>%\n  mutate(\n    pop_65_over = rowSums(select(., all_of(vars_65)), na.rm = TRUE)\n  ) %>%\n  select(GEOID, NAME, total_pop, med_income, pop_65_over)\n\ncensus_tracts <- census_tracts %>%\n  mutate(GEOID = as.character(GEOID))\n\nacs_pa <- acs_pa %>%\n  mutate(GEOID = as.character(GEOID))\n\npa_tracts_demo <- census_tracts %>%\n  left_join(acs_pa, by = \"GEOID\")\n\n# check\nnrow(pa_tracts_demo)                         \nsum(is.na(pa_tracts_demo$med_income))        \nmedian(pa_tracts_demo$med_income, na.rm=TRUE)\n```\n:::\n\n\n**Questions to answer:**\n- What year of ACS data are you using?\n2024 ACS 5-year estimates\n- How many tracts have missing income data?\n68 census tracts have missing median income data.\n- What is the median income across all PA census tracts?\nThe median household income across all Pennsylvania census tracts is $74,844\n\n---\n\n#### Step 3: Define Vulnerable Populations \n\nIdentify census tracts with vulnerable populations based on TWO criteria:\n1. Low median household income (choose an appropriate threshold)\n2. Significant elderly population (choose an appropriate threshold)\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Filter for vulnerable tracts based on your criteria\npa_tracts_demo <- pa_tracts_demo %>%\n  mutate(\n    pct_65_over = pop_65_over / total_pop\n  )\n\nincome_threshold  <- quantile(pa_tracts_demo$med_income, 0.25, na.rm = TRUE)\nelderly_threshold <- quantile(pa_tracts_demo$pct_65_over, 0.75, na.rm = TRUE)\n\nvulnerable_tracts <- pa_tracts_demo %>%\n  filter(\n    med_income <= income_threshold &\n    pct_65_over >= elderly_threshold\n  )\n\n# How many tracts meet criteria?\nn_vulnerable <- nrow(vulnerable_tracts)\n\n# Percent of PA tracts\npercent_vulnerable <- (n_vulnerable / nrow(pa_tracts_demo)) * 100\n```\n:::\n\n\n**Questions to answer:**\n- What income threshold did you choose and why?\nI defined low income as census tracts below the 25th percentile of median household income across Pennsylvania.Because it identifies the lowest-income quartile rather than using an arbitrary cutoff\n- What elderly population threshold did you choose and why?\nI defined significant elderly population as tracts above the 75th percentile of residents aged 65 and over. This captures areas with relatively high concentrations of elderly residents compared to the state distribution.\n- How many tracts meet your vulnerability criteria?\n156 tracts\n- What percentage of PA census tracts are considered vulnerable by your definition?\n4.53%\n\n---\n\n#### Step 4: Calculate Distance to Hospitals \n\nFor each vulnerable tract, calculate the distance to the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Transform to appropriate projected CRS\nvulnerable_proj <- st_transform(vulnerable_tracts, 2272)\nhospitals_proj  <- st_transform(hospitals, 2272)\n\ntract_centroids <- st_centroid(vulnerable_proj)\n\n\n# Calculate distance from each tract centroid to nearest hospital\n\ndist_matrix <- st_distance(tract_centroids, hospitals_proj)\n\nmin_dist_ft <- apply(dist_matrix, 1, min)\n\nmin_dist_miles <- as.numeric(min_dist_ft) / 5280\n\nvulnerable_proj$dist_to_hospital_mi <- min_dist_miles\n\n#check\nmean(vulnerable_proj$dist_to_hospital_mi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 4.618912\n```\n\n\n:::\n\n```{.r .cell-code}\nmax(vulnerable_proj$dist_to_hospital_mi)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 19.46594\n```\n\n\n:::\n\n```{.r .cell-code}\nsum(vulnerable_proj$dist_to_hospital_mi > 15)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use an appropriate projected coordinate system for Pennsylvania\n- Calculate distances in miles\n- Explain why you chose your projection\n\n**Questions to answer:**\n- What is the average distance to the nearest hospital for vulnerable tracts?\n4.62 miles\n- What is the maximum distance?\n19.47 miles\n- How many vulnerable tracts are more than 15 miles from the nearest hospital?\n10\n\nI transformed the data to NAD83, which is Pennsylvania South (EPSG:2272), becuase it is a State Plane coordinate system designed for Pennsylvania. This projection preserves distance measurements in feet, making it appropriate for converting and calculating  distances. Geographic coordinate systems such as WGS84 are unsuitable for distance calculations because their units are in degrees rather than linear distance.\n\n---\n\n#### Step 5: Identify Underserved Areas \n\nDefine \"underserved\" as vulnerable tracts that are more than 15 miles from the nearest hospital.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create underserved variable\nvulnerable_proj <- vulnerable_proj %>%\n  mutate(\n    underserved = dist_to_hospital_mi > 15\n  )\n\n#how many underserved\nn_underserved <- sum(vulnerable_proj$underserved)\nn_underserved\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n\n```{.r .cell-code}\npercent_underserved <- \n  (n_underserved / nrow(vulnerable_proj)) * 100\n\nround(percent_underserved, 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 6.41\n```\n\n\n:::\n:::\n\n\n**Questions to answer:**\n- How many tracts are underserved?\n10 vulnerable tracts are located more than 15 miles from the nearest hospital\n- What percentage of vulnerable tracts are underserved?\n6.41% of vulnerable tracts are classified as underserved under this definition.\n- Does this surprise you? Why or why not?\nIt is notable that some tracts are located more than 14 miles from the nearest hospital. These areas are likely rural and less densely developed, which may contribute to reduced access to healthcare services.\n\n---\n\n#### Step 6: Aggregate to County Level\n\nUse spatial joins and aggregation to calculate county-level statistics about vulnerable populations and hospital access.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join tracts to counties\ncounties_proj <- st_transform(pa_counties, st_crs(vulnerable_proj))\nvuln_with_county <- st_join(vulnerable_proj, counties_proj, join = st_within)\n\n\n# Aggregate statistics by county\ncounty_stats <- vuln_with_county %>%\n  st_drop_geometry() %>%\n  group_by(NAMELSADCO) %>%\n  summarise(\n    vulnerable_tracts = n(),\n    underserved_tracts = sum(underserved, na.rm = TRUE),\n    pct_underserved = 100 * underserved_tracts / vulnerable_tracts,\n    avg_dist_miles = mean(dist_to_hospital_mi, na.rm = TRUE),\n    total_vulnerable_pop = sum(total_pop, na.rm = TRUE)\n  ) %>%\n  arrange(desc(pct_underserved))\n```\n:::\n\n\n**Required county-level statistics:**\n- Number of vulnerable tracts\n- Number of underserved tracts  \n- Percentage of vulnerable tracts that are underserved\n- Average distance to nearest hospital for vulnerable tracts\n- Total vulnerable population\n\n**Questions to answer:**\n- Which 5 counties have the highest percentage of underserved vulnerable tracts?\nBradford, Huntingdon, Cameron, Dauphin, Wayne\n- Which counties have the most vulnerable people living far from hospitals?\nDauphin County\n- Are there any patterns in where underserved counties are located?\nCounties with higher shares of underserved vulnerable tracts tend to be more rural and lower-density, where hospitals are more dispersed and travel distances are longer compared to metropolitan counties.\n\n---\n\n#### Step 7: Create Summary Table \n\nCreate a professional table showing the top 10 priority counties for healthcare investment.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create and format priority counties table\nlibrary(knitr)\nlibrary(scales)\n\n\ntop10_priority <- county_stats %>%\n  arrange(desc(pct_underserved)) %>%\n  slice(1:10) %>%\n  mutate(\n    `County` = NAMELSADCO,  \n    `Vulnerable Tracts` = vulnerable_tracts,\n    `Underserved Tracts` = underserved_tracts,\n    `Percent Underserved (%)` = round(pct_underserved, 2),\n    `Average Distance (miles)` = round(avg_dist_miles, 2),\n    `Total Vulnerable Population` = comma(total_vulnerable_pop)\n  ) %>%\n  select(\n    County,\n    `Vulnerable Tracts`,\n    `Underserved Tracts`,\n    `Percent Underserved (%)`,\n    `Average Distance (miles)`,\n    `Total Vulnerable Population`\n  )\n\n# Formatted table\nkable(\n  top10_priority,\n  caption = \"Top 10 Priority Counties for Healthcare Investment Based on Percentage of Underserved Vulnerable Tracts\",\n  align = \"lccccc\"\n)\n```\n\n::: {.cell-output-display}\n\n\nTable: Top 10 Priority Counties for Healthcare Investment Based on Percentage of Underserved Vulnerable Tracts\n\n|County            | Vulnerable Tracts | Underserved Tracts | Percent Underserved (%) | Average Distance (miles) | Total Vulnerable Population |\n|:-----------------|:-----------------:|:------------------:|:-----------------------:|:------------------------:|:---------------------------:|\n|Bradford County   |         1         |         1          |         100.00          |          16.66           |            5,171            |\n|Cameron County    |         2         |         2          |         100.00          |          19.07           |            4,427            |\n|Forest County     |         1         |         1          |         100.00          |          18.13           |            2,552            |\n|Wayne County      |         3         |         2          |          66.67          |          14.30           |            5,932            |\n|Dauphin County    |         2         |         1          |          50.00          |          10.01           |            5,991            |\n|Huntingdon County |         2         |         1          |          50.00          |          16.33           |            7,107            |\n|Juniata County    |         2         |         1          |          50.00          |          12.56           |            5,575            |\n|Crawford County   |         3         |         1          |          33.33          |          10.57           |            6,794            |\n|Allegheny County  |        23         |         0          |          0.00           |           2.49           |           50,379            |\n|Armstrong County  |         3         |         0          |          0.00           |           6.00           |            9,951            |\n\n\n:::\n:::\n\n\n**Requirements:**\n- Use `knitr::kable()` or similar for formatting\n- Include descriptive column names\n- Format numbers appropriately (commas for population, percentages, etc.)\n- Add an informative caption\n- Sort by priority (you decide the metric)\n\n---\n\n## Part 2: Comprehensive Visualization \n\nUsing the skills from Week 3 (Data Visualization), create publication-quality maps and charts.\n\n### Map 1: County-Level Choropleth \n\nCreate a choropleth map showing healthcare access challenges at the county level.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create county-level access map\nlibrary(sf)\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(scales)\nlibrary(stringr)\n\ncounty_stats_clean <- county_stats %>%\n  rename(COUNTY_NAM = NAMELSADCO) %>%\n  mutate(\n    county_key = COUNTY_NAM %>%\n      str_remove(\"\\\\s+County$\") %>%\n      str_trim() %>%\n      str_to_upper()\n  ) %>%\n  st_drop_geometry()\n\nname_col <- intersect(\n  c(\"COUNTY_NAM\",\"NAMELSAD\",\"NAME\",\"NAME10\",\"COUNTYNAME\",\"COUNTY\"),\n  names(pa_counties)\n)[1]\n\npa_counties_clean <- pa_counties %>%\n  mutate(\n    county_key = .data[[name_col]] %>%\n      str_remove(\"\\\\s+County$\") %>%\n      str_trim() %>%\n      str_to_upper()\n  )\n\n#Join\ncounties_map <- pa_counties_clean %>%\n  left_join(county_stats_clean, by = \"county_key\")\n\ncounties_map <- counties_map %>%\n  mutate(pct_underserved = as.numeric(pct_underserved))\n\ncat(\"Counties total:\", nrow(counties_map), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCounties total: 67 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"pct_underserved NA:\", sum(is.na(counties_map$pct_underserved)), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npct_underserved NA: 21 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"pct_underserved range:\", paste(range(counties_map$pct_underserved, na.rm = TRUE), collapse = \" to \"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npct_underserved range: 0 to 100 \n```\n\n\n:::\n\n```{.r .cell-code}\n# Hospitals CRS match\nhospitals_map <- st_transform(hospitals, st_crs(counties_map))\n\n#Plot\nggplot() +\n  geom_sf(data = counties_map, aes(fill = pct_underserved), color = \"white\", linewidth = 0.2) +\n  geom_sf(data = hospitals_map, color = \"black\", size = 1.2, alpha = 0.75) +\n  scale_fill_viridis_c(\n    name = \"Underserved vulnerable tracts (%)\",\n    labels = label_percent(scale = 1),   \n    na.value = \"grey90\",\n    option = \"C\",\n    direction = -1\n  ) +\n  labs(\n    title = \"Healthcare Access Challenges in Pennsylvania\",\n    subtitle = \"Counties shaded by % of vulnerable tracts classified as underserved (distance > 15 miles); hospitals shown as points\",\n    caption = \"Source: ACS 2020–2024 (5-year) via tidycensus; hospital locations from course dataset. Underserved = vulnerable tracts > 15 miles from nearest hospital.\"\n  ) +\n  theme_void() +\n  theme(\n    legend.position = \"right\",\n    plot.title = element_text(size = 14, face = \"bold\"),\n    plot.subtitle = element_text(size = 10),\n    plot.caption = element_text(size = 8)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Fill counties by percentage of vulnerable tracts that are underserved\n- Include hospital locations as points\n- Use an appropriate color scheme\n- Include clear title, subtitle, and caption\n- Use `theme_void()` or similar clean theme\n- Add a legend with formatted labels\n\n---\n\n### Map 2: Detailed Vulnerability Map \n\nCreate a map highlighting underserved vulnerable tracts.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create detailed tract-level map\ntarget_crs <- st_crs(vulnerable_proj)\n\ntracts_map   <- st_transform(pa_tracts_demo, target_crs)\ncounties_map <- st_transform(pa_counties, target_crs)\nhosp_map     <- st_transform(hospitals, target_crs)\n\nvuln_all <- vulnerable_proj\nunderserved_tracts <- vuln_all %>% filter(underserved == TRUE)\nvulnerable_not_underserved <- vuln_all %>% filter(underserved == FALSE)\n\nggplot() +\n  # Background\n  geom_sf(data = tracts_map, fill = \"grey92\", color = NA) +\n\n  # County boundaries for context\n  geom_sf(data = counties_map, fill = NA, color = \"white\", linewidth = 0.4) +\n\n  # Vulnerable but not underserved (soft highlight)\n  geom_sf(data = vulnerable_not_underserved, fill = \"grey70\", color = NA, alpha = 0.7) +\n\n  # Underserved vulnerable tracts (strong highlight)\n  geom_sf(data = underserved_tracts, fill = \"red3\", color = \"white\", linewidth = 0.2) +\n\n  # Hospitals on top\n  geom_sf(data = hosp_map, color = \"black\", size = 0.8, alpha = 0.8) +\n\n  labs(\n    title = \"Underserved Vulnerable Census Tracts in Pennsylvania\",\n    subtitle = \"Underserved = vulnerable tracts located more than 15 miles from the nearest hospital\",\n    caption = \"Background tracts shown for context; county boundaries and hospital locations overlaid.\"\n  ) +\n  theme_void() +\n  theme(\n    plot.title = element_text(size = 14, face = \"bold\"),\n    plot.subtitle = element_text(size = 10),\n    plot.caption = element_text(size = 8)\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n:::\n\n\n**Requirements:**\n- Show underserved vulnerable tracts in a contrasting color\n- Include county boundaries for context\n- Show hospital locations\n- Use appropriate visual hierarchy (what should stand out?)\n- Include informative title and subtitle\n\n---\n\n### Chart: Distribution Analysis\n\nCreate a visualization showing the distribution of distances to hospitals for vulnerable populations.\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create distribution visualization\nlibrary(ggplot2)\n\nggplot(vulnerable_proj, aes(x = dist_to_hospital_mi)) +\n  geom_histogram(aes(y = ..density..),\n                 bins = 25,\n                 fill = \"steelblue\",\n                 color = \"white\",\n                 alpha = 0.7) +\n  geom_density(color = \"darkblue\", linewidth = 1) +\n  labs(\n    title = \"Distribution of Distance to Nearest Hospital\",\n    subtitle = \"Among Vulnerable Census Tracts in Pennsylvania\",\n    x = \"Distance to Nearest Hospital (miles)\",\n    y = \"Density\",\n    caption = \"Distances calculated from tract centroids to nearest hospital using projected CRS.\"\n  ) +\n  theme_minimal()\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\n\n**Suggested chart types:**\n- Histogram or density plot of distances\n- Box plot comparing distances across regions\n- Bar chart of underserved tracts by county\n- Scatter plot of distance vs. vulnerable population size\n\n**Requirements:**\n- Clear axes labels with units\n- Appropriate title\n- Professional formatting\n- Brief interpretation (1-2 sentences as a caption or in text)\nThe distribution of distances is strongly right-skewed, indicating that most vulnerable census tracts are located within approximately 5 miles of a hospital. However, a smaller subset of tracts experience substantially greater travel distances, extending beyond 15 miles. These long-distance tracts correspond to the underserved areas identified in the spatial analysis and are likely concentrated in more rural regions of the state.\n\n---\n\n## Part 3: Bring Your Own Data Analysis \n\nChoose your own additional spatial dataset and conduct a supplementary analysis.\n\n### Challenge Options\n\nChoose ONE of the following challenge exercises, or propose your own research question using OpenDataPhilly data (https://opendataphilly.org/datasets/). \n\n**Note these are just loose suggestions to spark ideas - follow or make your own as the data permits and as your ideas evolve. This analysis should include bringing in your own dataset, ensuring the projection/CRS of your layers align and are appropriate for the analysis (not lat/long or geodetic coordinate systems). The analysis portion should include some combination of spatial and attribute operations to answer a relatively straightforward question**\n\n---\n\n#### Education & Youth Services\n\n**Option A: Educational Desert Analysis**\n- **Data:** Schools, Libraries, Recreation Centers, Census tracts (child population)\n- **Question:** \"Which neighborhoods lack adequate educational infrastructure for children?\"\n- **Operations:** Buffer schools/libraries (0.5 mile walking distance), identify coverage gaps, overlay with child population density\n- **Policy relevance:** School district planning, library placement, after-school program siting\n\n**Option B: School Safety Zones**\n- **Data:** Schools, Crime Incidents, Bike Network\n- **Question:** \"Are school zones safe for walking/biking, or are they crime hotspots?\"\n- **Operations:** Buffer schools (1000ft safety zone), spatial join with crime incidents, assess bike infrastructure coverage\n- **Policy relevance:** Safe Routes to School programs, crossing guard placement\n\n---\n\n#### Environmental Justice\n\n**Option C: Green Space Equity** \n- **Data:** Parks, Street Trees, Census tracts (race/income demographics)\n- **Question:** \"Do low-income and minority neighborhoods have equitable access to green space?\"\n- **Operations:** Buffer parks (10-minute walk = 0.5 mile), calculate tree canopy or park acreage per capita, compare by demographics\n- **Policy relevance:** Climate resilience, environmental justice, urban forestry investment\n---\n\n#### Public Safety & Justice\n\n**Option D: Crime & Community Resources**\n- **Data:** Crime Incidents, Recreation Centers, Libraries, Street Lights\n- **Question:** \"Are high-crime areas underserved by community resources?\"\n- **Operations:** Aggregate crime counts to census tracts or neighborhoods, count community resources per area, spatial correlation analysis\n- **Policy relevance:** Community investment, violence prevention strategies\n---\n\n#### Infrastructure & Services\n\n**Option E: Polling Place Accessibility**\n- **Data:** Polling Places, SEPTA stops, Census tracts (elderly population, disability rates)\n- **Question:** \"Are polling places accessible for elderly and disabled voters?\"\n- **Operations:** Buffer polling places and transit stops, identify vulnerable populations, find areas lacking access\n- **Policy relevance:** Voting rights, election infrastructure, ADA compliance\n\n---\n\n#### Health & Wellness\n\n**Option F: Recreation & Population Health**\n- **Data:** Recreation Centers, Playgrounds, Parks, Census tracts (demographics)\n- **Question:** \"Is lack of recreation access associated with vulnerable populations?\"\n- **Operations:** Calculate recreation facilities per capita by neighborhood, buffer facilities for walking access, overlay with demographic indicators\n- **Policy relevance:** Public health investment, recreation programming, obesity prevention\n\n---\n\n#### Emergency Services\n\n**Option G: EMS Response Coverage**\n- **Data:** Fire Stations, EMS stations, Population density, High-rise buildings\n- **Question:** \"Are population-dense areas adequately covered by emergency services?\"\n- **Operations:** Create service area buffers (5-minute drive = ~2 miles), assess population coverage, identify gaps in high-density areas\n- **Policy relevance:** Emergency preparedness, station siting decisions\n\n---\n\n#### Arts & Culture\n\n**Option H: Cultural Asset Distribution**\n- **Data:** Public Art, Museums, Historic sites/markers, Neighborhoods\n- **Question:** \"Do all neighborhoods have equitable access to cultural amenities?\"\n- **Operations:** Count cultural assets per neighborhood, normalize by population, compare distribution across demographic groups\n- **Policy relevance:** Cultural equity, tourism, quality of life, neighborhood identity\n\n---\n\n### Data Sources\n\n**OpenDataPhilly:** https://opendataphilly.org/datasets/\n- Most datasets available as GeoJSON, Shapefile, or CSV with coordinates\n- Always check the Metadata for a data dictionary of the fields.\n\n**Additional Sources:**\n- **Pennsylvania Open Data:** https://data.pa.gov/\n- **Census Bureau (via tidycensus):** Demographics, economic indicators, commute patterns\n- **TIGER/Line (via tigris):** Geographic boundaries\n\n### Recommended Starting Points\n\n**If you're feeling confident:** Choose an advanced challenge with multiple data layers. \n**If you are a beginner, choose something more manageable that helps you understand the basics**\n\n\n**If you have a different idea:** Propose your own question! Just make sure:\n- You can access the spatial data\n- You can perform at least 2 spatial operations\n\n### Your Analysis\n\n**Your Task:**\n\n1. **Find and load additional data**\n   - Document your data source\n   - Check and standardize the CRS\n   - Provide basic summary statistics\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load your additional dataset\nlibrary(ggplot2)\nlibrary(httr)\nlibrary(jsonlite)\n\nschools <- st_read(\"data/Schools.shp\")\nbike <- st_read(\"data/Bike_Network.shp\")\n\n# As suggested on the OpenDataPhilly website, uses Carto’s SQL API to retrieve data \nread_carto_geojson <- function(sql) {\n  base <- \"https://phl.carto.com/api/v2/sql\"\n  url <- paste0(base, \"?q=\", URLencode(sql, reserved = TRUE), \"&format=GeoJSON\")\n  st_read(url, quiet = TRUE)\n}\n\ncrime_sql <- \"\nSELECT *\nFROM incidents_part1_part2\nWHERE dispatch_date_time >= '2024-01-01'\n  AND dispatch_date_time <  '2025-01-01'\nLIMIT 50000\n\"\n\ncrime <- read_carto_geojson(crime_sql)\n\nnrow(crime)\nst_crs(crime)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_crs(crime)\nst_crs(schools)\nst_crs(bike)\n\ntarget_crs <- 2272\n\ncrime   <- st_transform(crime, target_crs)\nschools <- st_transform(schools, target_crs)\nbike    <- st_transform(bike, target_crs)\n\nnrow(schools)\nnrow(crime)\nnrow(bike)\n```\n:::\n\n\n\n**Questions to answer:**\n- What dataset did you choose and why?\nSchools, crime incidents, and bike network to evaluate safety exposure and infrastructure coverage\n- What is the data source and date?\nOpenDataPhilly, 2024-2025\n- How many features does it contain?\nschools 490, crime 50000, bike 5225\n- What CRS is it in? Did you need to transform it?\nyes, I transformed to 2272\n\n---\n\n2. **Pose a research question**\n\nWrite a clear research statement that your analysis will answer.\n\nAre Philadelphia school zones (within 1,000 feet of schools) exposed to high crime activity, and do these zones have adequate bike infrastructure coverage to support safe walking and biking?\n\n---\n\n3. **Conduct spatial analysis**\n\nUse at least TWO spatial operations to answer your research question.\n\n**Required operations (choose 2+):**\n- Buffers\n- Spatial joins\n- Spatial filtering with predicates\n- Distance calculations\n- Intersections or unions\n- Point-in-polygon aggregation\n\n**Your Task:**\n\n::: {.cell}\n\n```{.r .cell-code}\n# Your spatial analysis\n# Create 1000 ft safety zone around schools\nschool_buffer <- st_buffer(schools, dist = 1000)\n\n# Spatial join crime points into buffers\ncrime_in_buffers <- st_join(school_buffer, crime, join = st_intersects)\n\n# Count crimes per school zone\ncrime_summary <- crime_in_buffers %>%\n  group_by(school_nam) %>%\n  summarise(crime_count = n())\n\n#Intersect bike network with school buffers.\nbike_in_buffers <- st_intersection(bike, school_buffer)\n\n# Calculate total bike lane length inside safety zones\nbike_length <- bike_in_buffers %>%\n  mutate(length_ft = st_length(geometry)) %>%\n  summarise(total_bike_ft = sum(length_ft))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncrime_near_schools <- crime[st_intersects(crime, st_union(school_buffer), sparse = FALSE), ]\n\n#Map\nggplot() +\n  geom_sf(data = school_buffer, aes(fill = \"School safety zone (1000 ft)\"),\n          alpha = 0.15, color = NA) +\n  geom_sf(data = bike, aes(color = \"Bike network\"),\n          linewidth = 0.4) +\n  geom_sf(data = crime_near_schools, aes(color = \"Crime incident\"),\n          alpha = 0.35, size = 0.5) +\n  geom_sf(data = schools, aes(color = \"School\"),\n          size = 0.9) +\n  scale_color_manual(\n    name = NULL,\n    values = c(\"Bike network\" = \"green\",\n               \"Crime incident\" = \"red\",\n               \"School\" = \"black\")\n  ) +\n  scale_fill_manual(\n    name = NULL,\n    values = c(\"School safety zone (1000 ft)\" = \"purple\")\n  ) +\n  theme_minimal() +\n  labs(\n    title = \"School Safety Zones (1000 ft)\",\n    subtitle = \"Crime incidents and bike network coverage near schools\"\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#rank schools by crime inside 1000 ft\ncrime_join <- st_join(school_buffer, crime, join = st_intersects)\n\ncrime_by_school <- crime_join %>%\n  st_drop_geometry() %>%\n  group_by(school_nam) %>%     \n  summarise(crime_count = n())\n\n# join counts back onto buffer geometry\nschool_buffer2 <- school_buffer %>%\n  left_join(crime_by_school, by = \"school_nam\") %>%\n  mutate(crime_count = ifelse(is.na(crime_count), 0, crime_count))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Create crime exposure categories using distribution-based cutoffs\nsummary(school_buffer2$crime_count)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n   1.00   32.00   55.00   83.56   97.00  860.00 \n```\n\n\n:::\n\n```{.r .cell-code}\nquantile(school_buffer2$crime_count,\n         probs = c(0, .25, .5, .75, .9, 1),\n         na.rm = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   0%   25%   50%   75%   90%  100% \n  1.0  32.0  55.0  97.0 139.2 860.0 \n```\n\n\n:::\n\n```{.r .cell-code}\nschool_buffer2 <- school_buffer2 %>%\n  mutate(crime_level = case_when(\n    crime_count >= 140 ~ \"Very high\",\n    crime_count >= 98 ~ \"High\",\n    crime_count >= 55 ~ \"Moderate\",\n    TRUE ~ \"Low\"\n  ))\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Hotspot map\nggplot() +\n  geom_sf(data = school_buffer2, aes(fill = crime_level),\n          color = NA, alpha = 0.75) +\n  geom_sf(data = bike, color = \"azure4\", linewidth = 0.35) +\n  geom_sf(data = schools, color = \"black\", size = 0.6) +\n  theme_void() +\n  labs(\n    title = \"Crime Exposure Within 1000 ft of Schools\",\n    subtitle = \"School safety zones grouped by crime exposure; bike network shown in grey\",\n    fill = \"Crime level\"\n  )\n```\n\n::: {.cell-output-display}\n![](lab2_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n:::\n\n\n\n**Analysis requirements:**\n- Clear code comments explaining each step\n- Appropriate CRS transformations\n- Summary statistics or counts\n- At least one map showing your findings\n- Brief interpretation of results (3-5 sentences)\n\n**Your interpretation:**\n\nCrime exposure within 1,000 feet of schools varies substantially across Philadelphia. The majority of school safety zones, according to distribution-based thresholds, are classified as having low to moderate crime rates, but a smaller subset exhibits high or extremely high incident counts, suggesting concentrated hotspots. The coverage of bike networks varies by school zone, and there is a lack of bike infrastructure or it is dispersed in some high-crime regions. These findings imply that focused safety interventions, like improved corridors and crossing-support initiatives, should be given priority in Safe Routes to School initiatives for schools with high criminal exposure and little bike network presence.\n\n\n## Finally - A few comments about your incorporation of feedback!\nTake a few moments to clean up your markdown document and then write a line or two or three about how you may have incorporated feedback that you recieved after your first assignment. \n\nI revised the file to remove excess instructional text I also learned how to suppress unnecessary datasets and data tables in the output, which improved readability and made the final page cleaner and more professional.\n\n---\n\n",
    "supporting": [
      "lab2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}