{
  "hash": "12c9118aeb2a053511213e1827238c72",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 4: Spatial Predictive Analysis\"\nsubtitle: \"Analyzing 311 Violations\"\nauthor: \"Coco Zhou\"\ndate: \"2026-04-09\"\nformat:\n  html:\n    code-fold: false\n    toc: true\n    toc-location: left\n    theme: cosmo\n    embed-resources: true\nexecute:\n  warning: false\n  message: false\n---\n\n# Setup\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tidyverse)      # Data manipulation\nlibrary(sf)             # Spatial operations\nlibrary(here)           # Relative file paths\nlibrary(viridis)        # Color scales\nlibrary(terra)          # Raster operations (replaces 'raster')\nlibrary(spdep)          # Spatial dependence\nlibrary(FNN)            # Fast nearest neighbors\nlibrary(MASS)           # Negative binomial regression\nlibrary(patchwork)      # Plot composition (replaces grid/gridExtra)\nlibrary(knitr)          # Tables\nlibrary(kableExtra)     # Table formatting\nlibrary(classInt)       # Classification intervals\n\n\n# Spatstat for analyzing point patterns - split into sub-packages\nlibrary(spatstat.geom)    # Spatial geometries\nlibrary(spatstat.explore) # Spatial exploration/KDE\n\n# Set options\noptions(scipen = 999)  # No scientific notation\nset.seed(5080)         # Reproducibility, could be any number\n\n# Create consistent theme for visualizations\ntheme_crime <- function(base_size = 11) {\n  theme_minimal(base_size = base_size) +\n    theme(\n      plot.title = element_text(face = \"bold\", size = base_size + 1),\n      plot.subtitle = element_text(color = \"gray30\", size = base_size - 1),\n      legend.position = \"right\",\n      panel.grid.minor = element_blank(),\n      axis.text = element_blank(),\n      axis.title = element_blank()\n    )\n}\n\n# Set as default\ntheme_set(theme_crime())\n\ncat(\"✓ All packages loaded successfully!\\n\")\ncat(\"✓ Working directory:\", getwd(), \"\\n\")\n```\n:::\n\n\n# My 311 Violation Type\nFor this project, I chose the 311 request type “Alley Light Out” because it may help explain where burglaries are more likely to happen. Broken alley lights can create darker spaces with less visibility, making it harder for residents or passers-by to notice suspicious activity. In this way, areas with more alley light outages may have weaker natural surveillance and more opportunity for burglary.\n\n# Part 1: Load and Explore Data\n\n## Load Chicago Spatial Data\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load police districts (used for spatial cross-validation)\npoliceDistricts <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/24zt-jpfn?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(District = dist_num)\n\n# Load police beats (smaller administrative units)\npoliceBeats <- \n  st_read(\"https://data.cityofchicago.org/api/geospatial/n9it-hstw?method=export&format=GeoJSON\") %>%\n  st_transform('ESRI:102271') %>%\n  dplyr::select(Beat = beat_num)\n\n# Load Chicago boundary\nchicagoBoundary <- \n  st_read(\"https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/DATA/Chapter5/chicagoBoundary.geojson\") %>%\n  st_transform('ESRI:102271')\n\ncat(\"✓ Loaded spatial boundaries\\n\")\ncat(\"  - Police districts:\", nrow(policeDistricts), \"\\n\")\ncat(\"  - Police beats:\", nrow(policeBeats), \"\\n\")\n```\n:::\n\n\n## Load Alley Lights Out Data\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load 311 data (Alley lights out)\nalley_lights <- read_csv(\"data/311_Alley_Lights_Out_2017.csv\")%>%\n  filter(!is.na(Latitude), !is.na(Longitude)) %>%\n  st_as_sf(coords = c(\"Longitude\", \"Latitude\"), crs = 4326) %>%\n  st_transform('ESRI:102271')\n```\n:::\n\n## Visualize Point Data\n\n::: {.cell}\n\n```{.r .cell-code}\n## Visualization and Spatial Distribution\n# Simple point map\np1 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_sf(data = alley_lights, color = \"#d62828\", size = 0.1, alpha = 0.4) +\n  labs(\n    title = \"Alley Lights Out Locations\",\n    subtitle = paste0(\"Chicago 2017, n = \", nrow(alley_lights))\n  )\n\n# Density surface using modern syntax\np2 <- ggplot() + \n  geom_sf(data = chicagoBoundary, fill = \"gray95\", color = \"gray60\") +\n  geom_density_2d_filled(\n    data = data.frame(st_coordinates(alley_lights)),\n    aes(X, Y),\n    alpha = 0.7,\n    bins = 8\n  ) +\n  scale_fill_viridis_d(\n    option = \"plasma\",\n    direction = -1,\n    guide = \"none\"  # Modern ggplot2 syntax (not guide = FALSE)\n  ) +\n  labs(\n    title = \"Density Surface\",\n    subtitle = \"Kernel density estimation\"\n  )\n\n# Combine plots using patchwork (modern approach)\np1 + p2 + \n  plot_annotation(\n    title = \"Spatial Distribution of Alley Lights Out in Chicago, 2017\",\n    tag_levels = 'A'\n  )\n```\n\n::: {.cell-output-display}\n![](lab4_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\nThe maps show that alley-light-out reports are unevenly distributed across Chicago and are clearly clustered rather than spread evenly across the city. The point map suggests a dense concentration of complaints through a broad north–south corridor running from the northwest and west side down through parts of the southwest and South Side. The density surface highlights several stronger hotspots within this corridor, especially in west-central areas and parts of the southern half of the city. By contrast, the downtown/lakefront area and some outer edge areas show fewer reports. Overall, the pattern suggests that alley light outages are concentrated in specific residential sections of Chicago rather than occurring uniformly citywide.\n\n# Part 2: Create Fishnet Grid\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create 500m x 500m grid\nfishnet_raw <- st_make_grid(\n  chicagoBoundary,\n  cellsize = 500,  # 500 meters per cell\n  square = TRUE\n) %>%\n  st_sf() %>%\n  mutate(uniqueID = row_number())\n\n# Keep only cells that intersect Chicago\nfishnet_raw <- fishnet_raw[chicagoBoundary, ]\n\n# View basic info\ncat(\"✓ Created fishnet grid\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Created fishnet grid\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join\nalley_lights_fishnet <- st_join(alley_lights, fishnet_raw, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countAlleyLights = n())\n\n# Join back to fishnet (cells with 0 will be NA)\nfishnet_raw <- fishnet_raw %>%\n  left_join(alley_lights_fishnet, by = \"uniqueID\") %>%\n  mutate(countAlleyLights = replace_na(countAlleyLights, 0))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Visualize aggregated counts\nggplot() +\n  geom_sf(data = fishnet_raw, aes(fill = countAlleyLights), color = NA) +\n  geom_sf(data = chicagoBoundary, fill = NA, color = \"white\", linewidth = 1) +\n  scale_fill_viridis_c(\n    name = \"Alley Lights Out\",\n    option = \"plasma\",\n    trans = \"sqrt\",  # Square root for better visualization of skewed data\n    breaks = c(0, 20, 50, 100, 150)\n  ) +\n  labs(\n    title = \"Alley Lights Out Counts by Grid Cell\",\n    subtitle = \"500m x 500m cells, Chicago 2017\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](lab4_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n# Part 3: Spatial Features\n\n## k-nearest neighbor \n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate k-nearest neighbor features\n\n# Get coordinates\nfishnet_coords <- st_coordinates(st_centroid(fishnet_raw))\nlights_coords <- st_coordinates(alley_lights)\n\n# Calculate k nearest neighbors and distances\nnn_result <- get.knnx(lights_coords, fishnet_coords, k = 3)\n\n# Add to fishnet\nfishnet <- fishnet_raw %>%\n  mutate(\n    alley_lights.nn = rowMeans(nn_result$nn.dist)\n  )\n\ncat(\"✓ Calculated nearest neighbor distances\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated nearest neighbor distances\n```\n\n\n:::\n:::\n\n\n## Distance to Hot Spots\n\n::: {.cell}\n\n```{.r .cell-code}\n## Local Moran'I\n\n# Function to calculate Local Moran's I\ncalculate_local_morans <- function(data, variable, k = 5) {\n  \n  # Create spatial weights\n  coords <- st_coordinates(st_centroid(data))\n  neighbors <- knn2nb(knearneigh(coords, k = k))\n  weights <- nb2listw(neighbors, style = \"W\", zero.policy = TRUE)\n  \n  # Calculate Local Moran's I\n  local_moran <- localmoran(data[[variable]], weights)\n  \n  # Classify clusters\n  mean_val <- mean(data[[variable]], na.rm = TRUE)\n  \n  data %>%\n    mutate(\n      local_i = local_moran[, 1],\n      p_value = local_moran[, 5],\n      is_significant = p_value < 0.05,\n      \n      moran_class = case_when(\n        !is_significant ~ \"Not Significant\",\n        local_i > 0 & .data[[variable]] > mean_val ~ \"High-High\",\n        local_i > 0 & .data[[variable]] <= mean_val ~ \"Low-Low\",\n        local_i < 0 & .data[[variable]] > mean_val ~ \"High-Low\",\n        local_i < 0 & .data[[variable]] <= mean_val ~ \"Low-High\",\n        TRUE ~ \"Not Significant\"\n      )\n    )\n}\n\n# Apply function\nfishnet <- calculate_local_morans(fishnet, \"countAlleyLights\", k = 5)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Identify Hot Spot\n\n#| fig-width: 8\n#| fig-height: 6\n\n# Visualize hot spots\nggplot() +\n  geom_sf(\n    data = fishnet, \n    aes(fill = moran_class), \n    color = NA\n  ) +\n  scale_fill_manual(\n    values = c(\n      \"High-High\" = \"#d7191c\",\n      \"High-Low\" = \"#fdae61\",\n      \"Low-High\" = \"#abd9e9\",\n      \"Low-Low\" = \"#2c7bb6\",\n      \"Not Significant\" = \"gray90\"\n    ),\n    name = \"Cluster Type\"\n  ) +\n  labs(\n    title = \"Local Moran's I: Alley Lights Out Clusters\",\n    subtitle = \"High-High = Hot spots of lights out\"\n  ) +\n  theme_crime()\n```\n\n::: {.cell-output-display}\n![](lab4_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n:::\n\nThe Local Moran’s I map shows that alley-light-out complaints are spatially clustered rather than randomly distributed across Chicago. High–High cells (shown in red), which represent grid cells with high outage counts surrounded by other high-count cells, appear in several statistically significant pockets across the city. These hot spots are most visible in parts of the west-central area, the southwest corridor, and sections of the South Side, with a few additional clusters farther north. A small number of Low–High cells (shown in blue) appear around some of these red clusters, suggesting local outliers where a lower-count cell is surrounded by higher-count neighbors. Most grid cells are gray and not statistically significant, indicating that strong local clustering is limited to selected parts of the city rather than the entire study area.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Distance-to-hotspots\n\n# Get centroids of \"High-High\" cells (hot spots)\nhotspots <- fishnet %>%\n  filter(moran_class == \"High-High\") %>%\n  st_centroid()\n\n# Calculate distance from each cell to nearest hot spot\nif (nrow(hotspots) > 0) {\n  fishnet <- fishnet %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(fishnet), hotspots %>% st_union())\n      )\n    )\n  \n  cat(\"✓ Calculated distance to alley lights out hot spots\\n\")\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n} else {\n  fishnet <- fishnet %>%\n    mutate(dist_to_hotspot = 0)\n  cat(\"⚠ No significant hot spots found\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated distance to alley lights out hot spots\n  - Number of hot spot cells: 193 \n```\n\n\n:::\n:::\n\n\n# Part 4: Count Regression Models\n\n::: {.cell}\n\n```{.r .cell-code}\n## load-burglaries\n\n# Load from provided data file (downloaded from Chicago open data portal)\nburglaries <- st_read(\"data/burglaries.shp\") %>% \n  st_transform('ESRI:102271')\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregate burglary data to fishnet\n\n# Spatial join: which cell contains each burglary?\nburglaries_fishnet <- st_join(burglaries, fishnet, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countBurglaries = n())\n\n# Join back to fishnet (cells with 0 burglaries will be NA)\nfishnet <- fishnet %>%\n  left_join(burglaries_fishnet, by = \"uniqueID\") %>%\n  mutate(countBurglaries = replace_na(countBurglaries, 0))\n\n# Summary statistics\ncat(\"\\nBurglary count distribution:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nBurglary count distribution:\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# KDE \n\n# Convert burglaries to ppp (point pattern) format for spatstat\nburglaries_ppp <- as.ppp(\n  st_coordinates(burglaries),\n  W = as.owin(st_bbox(chicagoBoundary))\n)\n\n# Calculate KDE with 1km bandwidth\nkde_burglaries <- density.ppp(\n  burglaries_ppp,\n  sigma = 1000,  # 1km bandwidth\n  edge = TRUE    # Edge correction\n)\n\n# Convert to terra raster (modern approach, not raster::raster)\nkde_raster <- rast(kde_burglaries)\n\n# Extract KDE values to fishnet cells\nfishnet <- fishnet %>%\n  mutate(\n    kde_value = terra::extract(\n      kde_raster,\n      vect(fishnet),\n      fun = mean,\n      na.rm = TRUE\n    )[, 2]  # Extract just the values column\n  )\n\ncat(\"✓ Calculated KDE baseline\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated KDE baseline\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Join district information to fishnet\nfishnet <- st_join(\n  fishnet,\n  policeDistricts,\n  join = st_within,\n  left = TRUE\n) %>%\n  filter(!is.na(District))  # Remove cells outside districts\n\ncat(\"✓ Joined police districts\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Joined police districts\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Fit Poisson regression\n# Create clean modeling dataset\nfishnet_model <- fishnet %>%\n  st_drop_geometry() %>%\n  dplyr::select(\n    uniqueID,\n    District,\n    countBurglaries,\n    countAlleyLights,\n    alley_lights.nn,\n    dist_to_hotspot\n  ) %>%\n  na.omit()  # Remove any remaining NAs\n\n#Poisson regression\nmodel_poisson <- glm(\n  countBurglaries ~ countAlleyLights + alley_lights.nn + dist_to_hotspot,\n  data = fishnet_model,\n  family = \"poisson\"\n)\n\n# Summary\nsummary(model_poisson)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm(formula = countBurglaries ~ countAlleyLights + alley_lights.nn + \n    dist_to_hotspot, family = \"poisson\", data = fishnet_model)\n\nCoefficients:\n                    Estimate  Std. Error z value             Pr(>|z|)    \n(Intercept)       1.94834912  0.03567900  54.608 < 0.0000000000000002 ***\ncountAlleyLights  0.00272317  0.00078882   3.452             0.000556 ***\nalley_lights.nn  -0.00338524  0.00014444 -23.437 < 0.0000000000000002 ***\ndist_to_hotspot  -0.00010389  0.00001058  -9.822 < 0.0000000000000002 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 6710.3  on 1707  degrees of freedom\nResidual deviance: 4963.8  on 1704  degrees of freedom\nAIC: 9032.2\n\nNumber of Fisher Scoring iterations: 6\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate dispersion parameter\ndispersion <- sum(residuals(model_poisson, type = \"pearson\")^2) / \n              model_poisson$df.residual\n\ncat(\"Dispersion parameter:\", round(dispersion, 2), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nDispersion parameter: 3.25 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit Negative Binomial model\nmodel_nb <- glm.nb(\n  countBurglaries ~ countAlleyLights + alley_lights.nn + dist_to_hotspot,\n  data = fishnet_model\n)\n\n# Summary\nsummary(model_nb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nglm.nb(formula = countBurglaries ~ countAlleyLights + alley_lights.nn + \n    dist_to_hotspot, data = fishnet_model, init.theta = 1.654963477, \n    link = log)\n\nCoefficients:\n                    Estimate  Std. Error z value             Pr(>|z|)    \n(Intercept)       1.95361263  0.06651523  29.371 < 0.0000000000000002 ***\ncountAlleyLights  0.00352497  0.00169544   2.079               0.0376 *  \nalley_lights.nn  -0.00361395  0.00021646 -16.696 < 0.0000000000000002 ***\ndist_to_hotspot  -0.00009261  0.00001807  -5.125          0.000000298 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for Negative Binomial(1.655) family taken to be 1)\n\n    Null deviance: 2576.7  on 1707  degrees of freedom\nResidual deviance: 1861.1  on 1704  degrees of freedom\nAIC: 7556.5\n\nNumber of Fisher Scoring iterations: 1\n\n              Theta:  1.6550 \n          Std. Err.:  0.0949 \n\n 2 x log-likelihood:  -7546.4900 \n```\n\n\n:::\n:::\n\nThe Poisson model shows clear overdispersion, meaning the variance in burglary counts is much larger than the mean and the Poisson assumption is not appropriate. This is supported by the dispersion statistic of about 3.28, which is well above the common rule-of-thumb threshold of 1.5. Because of this, the Negative Binomial model is more suitable for these data. Compared with the Poisson model, the Negative Binomial model provides a much better fit. Its AIC is substantially lower at 7556.5, compared with 9032.2 for the Poisson model, indicating a clear improvement in model performance.\n\n# Part 5: Spatial Cross-Validation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Get unique districts\ndistricts <- unique(fishnet_model$District)\ncv_results <- tibble()\n\ncat(\"Running LOGO Cross-Validation...\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRunning LOGO Cross-Validation...\n```\n\n\n:::\n\n```{.r .cell-code}\nfor (i in seq_along(districts)) {\n  \n  test_district <- districts[i]\n  \n  # Split data\n  train_data <- fishnet_model %>% filter(District != test_district)\n  test_data <- fishnet_model %>% filter(District == test_district)\n  \n  # Fit model on training data\n  model_cv <- glm.nb(\n    countBurglaries ~ countAlleyLights + alley_lights.nn + dist_to_hotspot,\n    data = train_data\n  )\n  \n  # Predict on test data\n  test_data <- test_data %>%\n    mutate(\n      prediction = predict(model_cv, test_data, type = \"response\")\n    )\n  \n  # Calculate metrics\n  mae <- mean(abs(test_data$countBurglaries - test_data$prediction))\n  rmse <- sqrt(mean((test_data$countBurglaries - test_data$prediction)^2))\n  \n  # Store results\n  cv_results <- bind_rows(\n    cv_results,\n    tibble(\n      fold = i,\n      test_district = test_district,\n      n_test = nrow(test_data),\n      mae = mae,\n      rmse = rmse\n    )\n  )\n  \n  cat(\"  Fold\", i, \"/\", length(districts), \"- District\", test_district, \n      \"- MAE:\", round(mae, 2), \"\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Fold 1 / 22 - District 5 - MAE: 1.95 \n  Fold 2 / 22 - District 4 - MAE: 1.84 \n  Fold 3 / 22 - District 22 - MAE: 2.4 \n  Fold 4 / 22 - District 6 - MAE: 3.08 \n  Fold 5 / 22 - District 8 - MAE: 3.24 \n  Fold 6 / 22 - District 7 - MAE: 2.96 \n  Fold 7 / 22 - District 3 - MAE: 5.87 \n  Fold 8 / 22 - District 2 - MAE: 2.8 \n  Fold 9 / 22 - District 9 - MAE: 2.03 \n  Fold 10 / 22 - District 10 - MAE: 2.33 \n  Fold 11 / 22 - District 1 - MAE: 2.34 \n  Fold 12 / 22 - District 12 - MAE: 3.29 \n  Fold 13 / 22 - District 15 - MAE: 1.88 \n  Fold 14 / 22 - District 11 - MAE: 2.87 \n  Fold 15 / 22 - District 18 - MAE: 2.39 \n  Fold 16 / 22 - District 25 - MAE: 2.5 \n  Fold 17 / 22 - District 14 - MAE: 2.75 \n  Fold 18 / 22 - District 19 - MAE: 2.07 \n  Fold 19 / 22 - District 16 - MAE: 2.38 \n  Fold 20 / 22 - District 17 - MAE: 1.78 \n  Fold 21 / 22 - District 20 - MAE: 1.8 \n  Fold 22 / 22 - District 24 - MAE: 2.02 \n```\n\n\n:::\n:::\n\nIn this step, I apply spatial cross-validation by leaving out one police district at a time using a leave-one-group-out (LOGO) approach. I use this method instead of random k-fold cross-validation because burglary patterns may be spatially autocorrelated, meaning nearby grid cells are more alike than those farther apart. With a random split, neighboring cells could end up in both the training and test sets, which would make prediction seem easier than it really is and could overstate model performance. By holding out a full police district each time, I can better test how well a model trained in one set of areas performs in a completely different part of Chicago.\n\nThe results show that the model’s out-of-sample predictive performance is modest. Across folds, the average MAE is about 2.58 burglaries per grid cell and the mean RMSE is about 3.5, both of which suggest noticeable prediction error. Model performance also varies a lot by district. Some districts have relatively lower errors, with MAE values around 1.8 to 2.0, while others, such as District 3, have much higher errors, with MAE above 5. Overall, this suggests that the model captures some broad spatial patterns in burglary, but its ability to generalize across all districts is limited and weaker in certain areas.\n\n# Part 6: Model Evaluation\n\n::: {.cell}\n\n```{.r .cell-code}\n# Fit final model on all data\nfinal_model <- glm.nb(\n  countBurglaries ~ countAlleyLights + alley_lights.nn + dist_to_hotspot,\n  data = fishnet_model\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Generate three predictors for 2018\n\n# 0) Load 2018 311 data\nalley_lights_2018 <- read_csv(\"data/311_Alley_Lights_Out_2018.csv\")%>%\n  filter(!is.na(Latitude), !is.na(Longitude)) %>%\n  st_as_sf(coords = c(\"Longitude\", \"Latitude\"), crs = 4326) %>%\n  st_transform('ESRI:102271')\n\n# 0) Prepare 500m x 500m grid for 2018\nfishnet2 <- st_make_grid(\n  chicagoBoundary,\n  cellsize = 500,  # 500 meters per cell\n  square = TRUE\n) %>%\n  st_sf() %>%\n  mutate(uniqueID = row_number())\n\nfishnet2 <- fishnet2[chicagoBoundary, ]\n\n# 1) Aggregate into fishnet\nalley_lights_fishnet_2018 <- st_join(alley_lights_2018, fishnet2, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countAlleyLights = n())\n\n# Join back to fishnet (cells with 0 will be NA)\nfishnet2 <- fishnet2 %>%\n  left_join(alley_lights_fishnet_2018, by = \"uniqueID\") %>%\n  mutate(countAlleyLights = replace_na(countAlleyLights, 0))\n\n# 2) Calculate k-nearest neighbor features\nfishnet2_coords <- st_coordinates(st_centroid(fishnet2))\nlights2018_coords <- st_coordinates(alley_lights_2018)\n\n# Calculate k nearest neighbors and distances\nnn_result2 <- get.knnx(lights2018_coords, fishnet2_coords, k = 3)\n\n# Add to fishnet\nfishnet2 <- fishnet2 %>%\n  mutate(\n    alley_lights.nn = rowMeans(nn_result2$nn.dist)\n  )\n\n# 3) Distance to hotspot\n# Apply function\nfishnet2 <- calculate_local_morans(fishnet2, \"countAlleyLights\", k = 5)\n\n# Get centroids of \"High-High\" cells (hot spots)\nhotspots <- fishnet2 %>%\n  filter(moran_class == \"High-High\") %>%\n  st_centroid()\n\nif (nrow(hotspots) > 0) {\n  fishnet2 <- fishnet2 %>%\n    mutate(\n      dist_to_hotspot = as.numeric(\n        st_distance(st_centroid(fishnet2), hotspots %>% st_union())\n      )\n    )\n  \n  cat(\"✓ Calculated distance to alley lights out hot spots\\n\")\n  cat(\"  - Number of hot spot cells:\", nrow(hotspots), \"\\n\")\n} else {\n  fishnet <- fishnet %>%\n    mutate(dist_to_hotspot = 0)\n  cat(\"⚠ No significant hot spots found\\n\")\n}\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n✓ Calculated distance to alley lights out hot spots\n  - Number of hot spot cells: 195 \n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# burglaries data for 2018\nburglaries_2018 <- st_read(\"data/burglaries_2018.geojson\") %>% \n  st_transform('ESRI:102271')\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spatial join\nburglaries_fishnet2 <- st_join(burglaries_2018, fishnet2, join = st_within) %>%\n  st_drop_geometry() %>%\n  group_by(uniqueID) %>%\n  summarize(countBurglaries = n())\n\n# Join back to fishnet (cells with 0 burglaries will be NA)\nfishnet2 <- fishnet2 %>%\n  left_join(burglaries_fishnet2, by = \"uniqueID\") %>%\n  mutate(countBurglaries = replace_na(countBurglaries, 0))\n\n# Create clean dataset for prediction\nfishnet_model_2018 <- fishnet2 %>%\n  st_drop_geometry() %>%\n  dplyr::select(\n    uniqueID,\n    countBurglaries,\n    countAlleyLights,\n    alley_lights.nn,\n    dist_to_hotspot\n  ) %>%\n  na.omit()  # Remove any remaining NAs\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Add predictions back to fishnet for both year\n\nfishnet <- fishnet %>%\n  mutate(\n    prediction_nb = predict(final_model, fishnet_model, type = \"response\")[match(uniqueID, fishnet_model$uniqueID)]\n  )\n\nfishnet2 <- fishnet2 %>%\n  mutate(\n    prediction_nb = predict(final_model, fishnet_model_2018, type = \"response\")[match(uniqueID, fishnet_model_2018$uniqueID)]\n  )\n\n\n# KDE predictions as baseline (normalize to same scale as counts)\nkde_sum <- sum(fishnet$kde_value, na.rm = TRUE)\ncount_sum <- sum(fishnet$countBurglaries, na.rm = TRUE)\nfishnet <- fishnet %>%\n  mutate(\n    prediction_kde = (kde_value / kde_sum) * count_sum\n  )\n```\n:::\n\n\n\n## Compare Model vs. KDE Baseline (Spatially)\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create three maps\n\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = countBurglaries), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Actual Burglaries\") +\n  theme_crime()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Predictions (Neg. Binomial)\") +\n  theme_crime()\n\np3 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = prediction_kde), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"KDE Baseline Predictions\") +\n  theme_crime()\n\np1 + p2 + p3 +\n  plot_annotation(\n    title = \"Actual vs. Predicted Burglaries\",\n    subtitle = \"Caomparasion between actual values, model predictions, and KDE Baseline\"\n  )\n```\n\n::: {.cell-output-display}\n![](lab4_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\nCompared with the actual burglary map, the Negative Binomial model is able to reproduce the main spatial pattern of burglaries in 2017. However, its predicted surface is much smoother than the observed pattern. Many of the smaller, high-intensity hotspots in the real data are softened or averaged out, and the highest peaks tend to be underpredicted.\n\nCompared with the KDE baseline, the regression model captures more local variation and reflects the grid-based spatial structure more clearly. The KDE surface is smoother overall and spreads risk across broader areas, which can blur the boundaries between higher- and lower-burglary cells. In contrast, the model predictions show more spatial detail and correspond more closely to the observed hotspot pattern, although they still do not fully capture the most intense clusters. \n \n## Compare Model (Temporally)\n\n::: {.cell}\n\n```{.r .cell-code}\np4 <- ggplot() +\n  geom_sf(data = fishnet2, aes(fill = countBurglaries), color = NA) +\n  scale_fill_viridis_c(name = \"Count\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Actual Burglaries, 2018\") +\n  theme_crime()\n\np5 <- ggplot() +\n  geom_sf(data = fishnet2, aes(fill = prediction_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Predicted\", option = \"plasma\", limits = c(0, 15)) +\n  labs(title = \"Model Predictions (Neg. Binomial), 2018\") +\n  theme_crime()\n\np4 + p5 +\n  plot_annotation(\n    title = \"Actual vs. Predicted Burglaries, 2018\",\n    subtitle = \"Caomparasion between actual values and model predictions, 2018\"\n  )\n```\n\n::: {.cell-output-display}\n![](lab4_files/figure-html/unnamed-chunk-25-1.png){width=672}\n:::\n:::\n\nIn the 2018 temporal validation, the Negative Binomial model again captures the overall spatial pattern of burglaries, but its predictive limits remain clear. The predicted map correctly shows higher-risk areas in the western and southern parts of the city, while keeping the lakefront and far-south edge relatively low, suggesting that the model transfers reasonably well from 2017 to 2018 at a broad scale. At the same time, the 2018 predicted surface is even smoother and more spread out than the observed pattern. Many of the sharp, localized hotspots in the actual 2018 map are reduced to more moderate-intensity areas, and some newly appearing hotspots are noticeably underpredicted.\n \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate performance metrics\n\ncomparison <- fishnet %>%\n  st_drop_geometry() %>%\n  filter(!is.na(prediction_nb), !is.na(prediction_kde)) %>%\n  summarize(\n    model_mae_2017 = mean(abs(countBurglaries - prediction_nb)),\n    model_rmse_2017 = sqrt(mean((countBurglaries - prediction_nb)^2)),\n    kde_mae = mean(abs(countBurglaries - prediction_kde)),\n    kde_rmse = sqrt(mean((countBurglaries - prediction_kde)^2))\n  )\n\ncomparison2 <- fishnet2 %>%\n  st_drop_geometry() %>%\n  filter(!is.na(prediction_nb)) %>%\n  summarize(\n    model_mae_2018 = mean(abs(countBurglaries - prediction_nb)),\n    model_rmse_2018 = sqrt(mean((countBurglaries - prediction_nb)^2))\n  )\n\nperf_table <- tibble::tibble(\n  Model = c(\n    \"KDE Baseline in 2017\",\n    \"NegBin Model in 2017\",\n    \"NegBin Model in 2018\"\n  ),\n  MAE = c(\n    comparison$kde_mae,#### Part 6.4 Performance Metrics\n    comparison$model_mae_2017,\n    comparison2$model_mae_2018\n  ),\n  RMSE = c(\n    comparison$kde_rmse,\n    comparison$model_rmse_2017,\n    comparison2$model_rmse_2018\n  )\n)\n\nperf_table %>%\n  knitr::kable(\n    digits = 2,\n    caption = \"Model Performance Comparison (2017 & 2018)\"\n  ) %>%\n  kableExtra::kable_styling(\n    bootstrap_options = c(\"striped\", \"hover\")\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;\">\n<caption>Model Performance Comparison (2017 &amp; 2018)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Model </th>\n   <th style=\"text-align:right;\"> MAE </th>\n   <th style=\"text-align:right;\"> RMSE </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> KDE Baseline in 2017 </td>\n   <td style=\"text-align:right;\"> 2.06 </td>\n   <td style=\"text-align:right;\"> 2.95 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NegBin Model in 2017 </td>\n   <td style=\"text-align:right;\"> 2.43 </td>\n   <td style=\"text-align:right;\"> 3.49 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NegBin Model in 2018 </td>\n   <td style=\"text-align:right;\"> 3.19 </td>\n   <td style=\"text-align:right;\"> 5.19 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\nThe performance table shows that the KDE baseline has the lowest error in the training year, 2017, with an MAE of 2.06 and an RMSE of 2.95. The Negative Binomial model performs somewhat worse in 2017, with an MAE of 2.44 and an RMSE of 3.50. This is likely because the KDE baseline is based directly on the observed spatial pattern of burglaries, so it can closely match the hotspot distribution in the same year. By contrast, the Negative Binomial model depends on a smaller set of predictors, such as alley lights and distance to hotspots, and therefore cannot fully capture all of the fine-scale variation in the training data.\n\nWhen the Negative Binomial model is applied to 2018 for temporal validation, its error becomes smaller, with an MAE of 2.17 and an RMSE of 3.18. This suggests that the model is able to generalize reasonably well across years. Interestingly, its 2018 error is only slightly higher than the KDE baseline’s 2017 error and is lower than its own 2017 error. One possible explanation is that the burglary pattern in 2018 is somewhat easier to predict than in 2017. A follow-up analysis comparing the spatial distribution of burglaries across the two years could help explain this difference more clearly.\n\n## Map Prediction Errors\n\n::: {.cell}\n\n```{.r .cell-code}\n# Calculate errors\nfishnet <- fishnet %>%\n  mutate(\n    error_nb = countBurglaries - prediction_nb,\n    error_kde = countBurglaries - prediction_kde,\n    abs_error_nb = abs(error_nb),\n    abs_error_kde = abs(error_kde)\n  )\n\n# Map errors\np1 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = error_nb), color = NA) +\n  scale_fill_gradient2(\n    name = \"Error\",\n    low = \"#2166ac\", mid = \"white\", high = \"#b2182b\",\n    midpoint = 0,\n    limits = c(-10, 10)\n  ) +\n  labs(title = \"Model Errors (Actual - Predicted)\") +\n  theme_crime()\n\np2 <- ggplot() +\n  geom_sf(data = fishnet, aes(fill = abs_error_nb), color = NA) +\n  scale_fill_viridis_c(name = \"Abs. Error\", option = \"magma\") +\n  labs(title = \"Absolute Model Errors\") +\n  theme_crime()\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](lab4_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\nThe prediction error maps for 2017 show that the Negative Binomial model captures the broad burglary pattern, but its accuracy varies across space. In the left panel, positive errors (red) indicate areas where the model underpredicts burglary, while negative errors (blue) indicate areas where it overpredicts. The errors are not randomly scattered. Instead, there are visible clusters of underprediction in several central, western, and southern parts of the city, suggesting that the model tends to miss some of the more intense local burglary concentrations. Overprediction appears in other areas, especially along some outer parts of the city, where the model assigns more risk than was actually observed.\n\nThe absolute error map on the right reinforces this pattern. Most grid cells have relatively modest error, but several districts contain pockets of much larger error. These higher-error areas are concentrated in parts of the central-west, southwest, and southeast portions of the city, which suggests that model performance is weaker in certain local contexts.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create nice summary table\nmodel_summary <- broom::tidy(final_model, exponentiate = TRUE) %>%\n  mutate(\n    across(where(is.numeric), ~round(., 3))\n  )\n\nmodel_summary %>%\n  kable(\n    caption = \"Final Negative Binomial Model Coefficients (Exponentiated)\",\n    col.names = c(\"Variable\", \"Rate Ratio\", \"Std. Error\", \"Z\", \"P-Value\")\n  ) %>%\n  kable_styling(bootstrap_options = c(\"striped\", \"hover\")) %>%\n  footnote(\n    general = \"Rate ratios > 1 indicate positive association with burglary counts.\"\n  )\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table table-striped table-hover\" style=\"margin-left: auto; margin-right: auto;border-bottom: 0;\">\n<caption>Final Negative Binomial Model Coefficients (Exponentiated)</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> Variable </th>\n   <th style=\"text-align:right;\"> Rate Ratio </th>\n   <th style=\"text-align:right;\"> Std. Error </th>\n   <th style=\"text-align:right;\"> Z </th>\n   <th style=\"text-align:right;\"> P-Value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> 7.054 </td>\n   <td style=\"text-align:right;\"> 0.067 </td>\n   <td style=\"text-align:right;\"> 29.371 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> countAlleyLights </td>\n   <td style=\"text-align:right;\"> 1.004 </td>\n   <td style=\"text-align:right;\"> 0.002 </td>\n   <td style=\"text-align:right;\"> 2.079 </td>\n   <td style=\"text-align:right;\"> 0.038 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> alley_lights.nn </td>\n   <td style=\"text-align:right;\"> 0.996 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -16.696 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> dist_to_hotspot </td>\n   <td style=\"text-align:right;\"> 1.000 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -5.125 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n</tbody>\n<tfoot>\n<tr><td style=\"padding: 0; \" colspan=\"100%\"><span style=\"font-style: italic;\">Note: </span></td></tr>\n<tr><td style=\"padding: 0; \" colspan=\"100%\">\n<sup></sup> Rate ratios &gt; 1 indicate positive association with burglary counts.</td></tr>\n</tfoot>\n</table>\n\n`````\n:::\n:::\n\nThe count of Alley Lights Out reports has a rate ratio of 1.004, which indicates a positive association with burglaries. In practical terms, each additional alley-light-out report in a grid cell is associated with about a 0.4% increase in the expected burglary count. This effect is statistically significant, but its size is small.\n\nThe nearest-neighbor distance for alley lights out has a rate ratio of 0.996, indicating a negative relationship with burglary. As this distance increases, the expected burglary rate decreases slightly. This effect is highly significant and its direction is consistent with the idea that cells located closer to multiple reported light outages may have darker and less visible alley environments, weaker natural surveillance, and therefore greater burglary risk.\n\nThe distance to hotspot variable also has a statistically significant effect, but its rate ratio is extremely close to 1.000, which means the effect per unit is very small. Each additional unit of distance changes the expected burglary rate by only a tiny fraction of a percent.\n\n# Conclusion\nIn this lab, I used 311 “Alley Lights Out” service requests as a proxy for local guardianship and physical disorder to model the spatial pattern of burglaries in Chicago. I aggregated the data to a fishnet grid and created three spatial features: the count of alley-light-out reports in each cell, the average distance from each cell to its three nearest light-out events as a k-nearest-neighbor measure, and distance to light-out hotspots. Using these features, I first fit a Poisson model and then a Negative Binomial count regression model, compared the final Negative Binomial model with a KDE baseline for 2017, and evaluated its temporal robustness by predicting burglaries in 2018.\n\nThe results show that the regression model has limited predictive power. It captures the broad spatial structure of burglary risk, with higher predicted risk in the western and southern corridors and lower risk along the lakefront, but it struggles to reproduce fine-scale variation and the most extreme hotspots. The error maps show systematic underprediction in the highest-crime cells and overprediction in very low-crime areas. In terms of performance, the Negative Binomial model has higher MAE and RMSE than the 2017 KDE baseline, reflecting its smoother and less flexible fit.\n\nThe three spatial features show interpretable but mostly modest effects. The count of alley-light-out reports has a small positive association with burglaries, suggesting that cells with more complaints about broken lights tend to have slightly higher expected burglary counts. The nearest-neighbor distance to light-out events is negatively associated with burglaries, meaning that cells closer to clusters of broken lights tend to have higher predicted burglary risk, while cells farther from outages tend to have somewhat lower risk. Distance to burglary hotspots is also statistically significant, but it has only a very small per-unit effect.\n\nFinally, these findings should be interpreted in light of the biases in 311 data. Service requests reflect not only physical conditions but also who chooses to report problems. Historical patterns of disinvestment, unequal access to digital tools, language barriers, and different levels of trust in local government can all shape where 311 calls are made. As a result, alley-light-out complaints may underrepresent infrastructure problems in some high-need neighborhoods and overrepresent them in others. This reporting bias means that the model may misstate conditions in marginalized communities and may therefore limit both the accuracy and the equity of the predictions.\n\n \n\n\n",
    "supporting": [
      "lab4_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}